// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Zinc from "../../../index.js";

export declare namespace ManagedAccountsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ManagedAccountsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ManagedAccountsClient.Options>;

    constructor(options: ManagedAccountsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List all retailer credentials for the current user.
     * If is_global=True (admin only), list global credentials instead.
     *
     * @param {Zinc.ListRetailerCredentialsManagedAccountsGetRequest} request
     * @param {ManagedAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zinc.UnprocessableEntityError}
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.managedAccounts.listRetailerCredentials()
     */
    public listRetailerCredentials(
        request: Zinc.ListRetailerCredentialsManagedAccountsGetRequest = {},
        requestOptions?: ManagedAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Zinc.RetailerCredentialsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listRetailerCredentials(request, requestOptions));
    }

    private async __listRetailerCredentials(
        request: Zinc.ListRetailerCredentialsManagedAccountsGetRequest = {},
        requestOptions?: ManagedAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zinc.RetailerCredentialsListResponse>> {
        const { limit, offset, search, authorization } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            search,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ authorization: authorization ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                "managed-accounts",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Zinc.RetailerCredentialsListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Zinc.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZincError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/managed-accounts");
    }

    /**
     * Create new retailer credentials for the current user.
     * If is_global=True (admin only), creates global credentials owned by the system user.
     *
     * @param {Zinc.RetailerCredentialsCreate} request
     * @param {ManagedAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zinc.UnprocessableEntityError}
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.managedAccounts.createRetailerCredentials({
     *         email: "email"
     *     })
     */
    public createRetailerCredentials(
        request: Zinc.RetailerCredentialsCreate,
        requestOptions?: ManagedAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Zinc.RetailerCredentialsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createRetailerCredentials(request, requestOptions));
    }

    private async __createRetailerCredentials(
        request: Zinc.RetailerCredentialsCreate,
        requestOptions?: ManagedAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zinc.RetailerCredentialsResponse>> {
        const { authorization, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ authorization: authorization ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                "managed-accounts",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Zinc.RetailerCredentialsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Zinc.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZincError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/managed-accounts");
    }

    /**
     * Update retailer credentials for the current user.
     * Admins can also update global credentials.
     *
     * @param {Zinc.RetailerCredentialsUpdate} request
     * @param {ManagedAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zinc.UnprocessableEntityError}
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.managedAccounts.updateRetailerCredentials({
     *         short_id: "short_id"
     *     })
     */
    public updateRetailerCredentials(
        request: Zinc.RetailerCredentialsUpdate,
        requestOptions?: ManagedAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Zinc.RetailerCredentialsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateRetailerCredentials(request, requestOptions));
    }

    private async __updateRetailerCredentials(
        request: Zinc.RetailerCredentialsUpdate,
        requestOptions?: ManagedAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zinc.RetailerCredentialsResponse>> {
        const { short_id: shortId, authorization, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ authorization: authorization ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                `managed-accounts/${core.url.encodePathParam(shortId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Zinc.RetailerCredentialsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Zinc.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZincError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/managed-accounts/{short_id}");
    }

    /**
     * Delete retailer credentials for the current user.
     * Admins can also delete global credentials.
     *
     * @param {Zinc.DeleteRetailerCredentialsManagedAccountsShortIdDeleteRequest} request
     * @param {ManagedAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zinc.UnprocessableEntityError}
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.managedAccounts.deleteRetailerCredentials({
     *         short_id: "short_id"
     *     })
     */
    public deleteRetailerCredentials(
        request: Zinc.DeleteRetailerCredentialsManagedAccountsShortIdDeleteRequest,
        requestOptions?: ManagedAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteRetailerCredentials(request, requestOptions));
    }

    private async __deleteRetailerCredentials(
        request: Zinc.DeleteRetailerCredentialsManagedAccountsShortIdDeleteRequest,
        requestOptions?: ManagedAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { short_id: shortId, authorization } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ authorization: authorization ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                `managed-accounts/${core.url.encodePathParam(shortId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Zinc.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZincError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/managed-accounts/{short_id}",
        );
    }
}
