// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "https://example.com/zinc/webhook"
 *     }
 */
export interface WebhookEndpointUpdate {
    authorization?: string | null;
    /** Absolute http(s) URL that receives order and return events. */
    url: string;
}
