// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         token: "token"
 *     }
 */
export interface SandboxClaimRequest {
    authorization?: string | null;
    token: string;
}
