// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         product_id: "product_id",
 *         retailer: "retailer"
 *     }
 */
export interface GetProductOffersProductsProductIdOffersGetRequest {
    product_id: string;
    /** Retailer identifier: amazon, walmart, bestbuy, etsy, or a Shopify store's domain (e.g. retailer=yetch.studio) */
    retailer: string;
    /** Max response age in seconds (mutually exclusive with newer_than) */
    max_age?: number | null;
    /** Minimum retrieval timestamp (mutually exclusive with max_age) */
    newer_than?: number | null;
    /** Return immediately with status=processing */
    async?: boolean | null;
    authorization?: string | null;
}
