// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../../../../index.js";

/**
 * @example
 *     {
 *         product_id: "product_id",
 *         retailer: "amazon"
 *     }
 */
export interface GetProductOffersProductsProductIdOffersGetRequest {
    product_id: string;
    /** Retailer identifier */
    retailer: Zinc.GetProductOffersProductsProductIdOffersGetRequestRetailer;
    /** Max response age in seconds (mutually exclusive with newer_than) */
    max_age?: number | null;
    /** Minimum retrieval timestamp (mutually exclusive with max_age) */
    newer_than?: number | null;
    /** Return immediately with status=processing */
    async?: boolean | null;
    authorization?: string | null;
}
