// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "query",
 *         retailer: "retailer"
 *     }
 */
export interface SearchProductsProductsSearchGetRequest {
    /** Search term */
    query: string;
    /** Retailer identifier: amazon, walmart, bestbuy, etsy, or a Shopify store's domain (e.g. retailer=yetch.studio) */
    retailer: string;
    /** Page number for pagination */
    page?: number | null;
    /** Only return items that ship for free (Walmart and Best Buy: ship price of 0). Currently a no-op for Amazon: the upstream search data under-reports Prime, so filtering on it would drop valid items — Amazon results are returned unfiltered. Filtering happens after pagination, so per-page counts vary; use `next_page` in the response to keep paging — an empty page with a non-null `next_page` is not the end of results. Rejected for Shopify stores: their search data carries no shipping information, so the filter cannot be honored. */
    free_shipping?: boolean;
    authorization?: string | null;
}
