// This file was auto-generated by Fern from our API Definition.

export const AgentProductOffersPostRequestRetailer = {
    Amazon: "amazon",
    Walmart: "walmart",
} as const;
export type AgentProductOffersPostRequestRetailer =
    (typeof AgentProductOffersPostRequestRetailer)[keyof typeof AgentProductOffersPostRequestRetailer];
