// This file was auto-generated by Fern from our API Definition.

export const AgentProductDetailsRequestRetailer = {
    Amazon: "amazon",
    Walmart: "walmart",
} as const;
export type AgentProductDetailsRequestRetailer =
    (typeof AgentProductDetailsRequestRetailer)[keyof typeof AgentProductDetailsRequestRetailer];
