// This file was auto-generated by Fern from our API Definition.

export const AgentSearchRequestSort = {
    Relevance: "relevance",
    PriceAsc: "price_asc",
    PriceDesc: "price_desc",
    Rating: "rating",
} as const;
export type AgentSearchRequestSort = (typeof AgentSearchRequestSort)[keyof typeof AgentSearchRequestSort];
