// This file was auto-generated by Fern from our API Definition.

export const AgentProductSearchPostRequestRetailer = {
    Amazon: "amazon",
    Walmart: "walmart",
} as const;
export type AgentProductSearchPostRequestRetailer =
    (typeof AgentProductSearchPostRequestRetailer)[keyof typeof AgentProductSearchPostRequestRetailer];
