// This file was auto-generated by Fern from our API Definition.

/**
 * Product details, passed through from the retailer. Common fields are listed first; fields marked with a retailer name are only present in that retailer's payload. Anything the retailer returns that is not listed here is passed through as well.
 */
export interface AgentProductDetailsResponse {
    /** `completed` when the payload below is populated. `processing` when `async=true` was passed and the fetch is still running — poll again. `failed` when the retailer returned an error; see `code` and `message`. */
    status: AgentProductDetailsResponse.Status;
    /** Only on `status: failed`. Machine-readable error code, e.g. `product_not_found`, `invalid_request`. */
    code?: string | undefined;
    /** Only on `status: failed`. Human-readable explanation. */
    message?: string | undefined;
    /** Retailer that served the payload: `amazon`, `walmart`, `bestbuy`, `etsy`, or `shopify` (with the store's hostname in `domain`). */
    retailer?: string | undefined;
    /** Identifier you passed in: ASIN (Amazon), item id (Walmart), bsin (Best Buy), product handle (Shopify), or listing id (Etsy). */
    product_id?: string | undefined;
    /** Product title. */
    title?: (string | null) | undefined;
    /** Brand or manufacturer. Shopify: the store's `vendor`. Etsy: not set — see `shop_name`. */
    brand?: (string | null) | undefined;
    /** URL of the primary product image. */
    main_image?: (string | null) | undefined;
    /** URLs of all product images. */
    images?: string[] | undefined;
    /** Long-form description (Amazon, Walmart, Best Buy). Shopify and Etsy use `description`. */
    product_description?: (string | null) | undefined;
    /** Long-form description (Shopify, Etsy). Plain text on Etsy; may contain HTML on Shopify. */
    description?: (string | null) | undefined;
    /** Price in cents (minor units of `currency_code` on Etsy). Amazon: the buy-box price, which is not always present and is often not the cheapest offer — use the offers endpoint for pricing. Best Buy: the `New` condition price. Shopify: the default variant's price. */
    price?: (number | null) | undefined;
    /** Average product rating, 0–5 (Amazon, Walmart, Best Buy). Not set on Etsy — see `shop_review_average`. */
    stars?: (number | null) | undefined;
    /** Number of product reviews (Amazon, Walmart). */
    review_count?: (number | null) | undefined;
    /** Number of product reviews (Best Buy). */
    num_reviews?: (number | null) | undefined;
    /** Highlight bullets (Amazon, Walmart, Best Buy). */
    feature_bullets?: string[] | undefined;
    /** Specification lines, e.g. `Item model number: 5438` (Amazon, Walmart, Best Buy). */
    product_details?: string[] | undefined;
    /** Category breadcrumb, broadest first (Amazon, Walmart, Best Buy). */
    categories?: string[] | undefined;
    /** The variant axes and values that identify *this* product (Amazon, Walmart, Best Buy). */
    variant_specifics?: AgentProductDetailsResponse.VariantSpecifics.Item[] | undefined;
    /** Every sibling variant of this product and its identifier (Amazon, Walmart). */
    all_variants?: AgentProductDetailsResponse.AllVariants.Item[] | undefined;
    /** External product identifiers (Amazon, Walmart, Best Buy). */
    epids?: AgentProductDetailsResponse.Epids.Item[] | undefined;
    /** The same identifiers keyed by type, e.g. `{"UPC": "048526054381"}` (Amazon, Walmart). */
    epids_map?: Record<string, string> | undefined;
    /** Unix time the retailer page was retrieved (Amazon, Walmart). */
    timestamp?: number | undefined;
    /** Canonical product URL (Shopify, Etsy). */
    url?: (string | null) | undefined;
    /** Whether the product can currently be bought (Shopify, Etsy). Etsy: false while the shop is on vacation even if stock exists — see `shop_is_vacation`. */
    available?: (boolean | null) | undefined;
    /** Merchant-assigned tags (Shopify, Etsy). */
    tags?: string[] | undefined;
    /** Amazon only. The product's ASIN. */
    asin?: string | undefined;
    /** Amazon only. Crossed-out list price in cents, when the retailer shows one. */
    original_retail_price?: (number | null) | undefined;
    /** Amazon only. Shipping price in cents. */
    ship_price?: (number | null) | undefined;
    /** Amazon only. Number of customer questions. */
    question_count?: (number | null) | undefined;
    /** Amazon only. Shipping weight and package size. */
    package_dimensions?: AgentProductDetailsResponse.PackageDimensions | undefined;
    /** Amazon only. Author names, for books. */
    authors?: string[] | undefined;
    /** Amazon only. `present` when the listing has A+ marketing content. The HTML itself is not returned. */
    aplus_html?: string | undefined;
    /** Amazon only. Amazon Fresh item. */
    fresh?: boolean | undefined;
    /** Amazon only. Amazon Pantry item. */
    pantry?: boolean | undefined;
    /** Amazon only. Amazon Handmade item. */
    handmade?: boolean | undefined;
    /** Amazon only. Digital-only item (software, video, game codes). Zinc cannot order these. */
    digital?: boolean | undefined;
    /** Amazon only. `false` when the item cannot be ordered through Zinc; `true` when it might be. */
    buyapi_hint?: boolean | undefined;
    /** Best Buy only. Numeric SKU, for cross-referencing with search results (which return the SKU as `product_id`). */
    sku?: (string | null) | undefined;
    /** Best Buy only. Canonical product URL. */
    product_url?: string | undefined;
    /** Best Buy only. Price per condition (new plus each open-box grade). For Amazon and Walmart offers use the offers endpoint. */
    offers?: AgentProductDetailsResponse.Offers.Item[] | undefined;
    /** Shopify only. Store hostname you passed as `retailer`. */
    domain?: string | undefined;
    /** Shopify only. Product handle (same value as `product_id`). */
    handle?: string | undefined;
    /** Shopify only. The store's numeric product id. */
    shopify_product_id?: (string | null) | undefined;
    /** Shopify only. The store's product type. */
    product_type?: (string | null) | undefined;
    /** Shopify only. Cheapest variant price in cents. */
    price_min?: (number | null) | undefined;
    /** Shopify only. Most expensive variant price in cents. */
    price_max?: (number | null) | undefined;
    /** Etsy only. Listing id (same as `product_id`). */
    listing_id?: string | undefined;
    /** Etsy only. ISO 4217 currency of `price`, e.g. `USD`, `EUR`. Prices are not converted. */
    currency_code?: (string | null) | undefined;
    /** Etsy only. Units the shop has in stock. */
    quantity?: (number | null) | undefined;
    /** Etsy only. Listing state: `active`, `inactive`, `sold_out`, `expired`, … */
    state?: (string | null) | undefined;
    /** Etsy only. Materials listed by the shop. */
    materials?: string[] | undefined;
    /** Etsy only. Etsy's category id. No category name is returned. */
    taxonomy_id?: (number | null) | undefined;
    /** Etsy only. `i_did`, `someone_else`, or `collective`. */
    who_made?: (string | null) | undefined;
    /** Etsy only. Etsy's production-era bucket, e.g. `made_to_order`, `2020_2026`, `before_2006`. */
    when_made?: (string | null) | undefined;
    /** Etsy only. Craft supply, not a finished good. */
    is_supply?: (boolean | null) | undefined;
    /** Etsy only. Buyer can request customization. */
    is_customizable?: (boolean | null) | undefined;
    /** Etsy only. `physical`, `download`, or `both`. A download has nothing to ship. */
    listing_type?: (string | null) | undefined;
    /** Etsy only. Users who favorited the listing. */
    num_favorers?: (number | null) | undefined;
    /** Etsy only. Listing view count. */
    views?: (number | null) | undefined;
    /** Etsy only. Whether the listing has variants at all. When true but `variants` is empty, Etsy did not expose the inventory matrix. */
    has_variations?: (boolean | null) | undefined;
    /** Etsy only. Selling shop's name. */
    shop_name?: (string | null) | undefined;
    /** Etsy only. Selling shop's URL. */
    shop_url?: (string | null) | undefined;
    /** Etsy only. The **shop's** average rating over the past year, 0–5. Null when the shop has no recent reviews. */
    shop_review_average?: (number | null) | undefined;
    /** Etsy only. The shop's review count over the past year. */
    shop_review_count?: (number | null) | undefined;
    /** Etsy only. Shop is on vacation mode. */
    shop_is_vacation?: (boolean | null) | undefined;
    /** Shopify and Etsy only. Per-variant price and availability. Amazon and Walmart use `variant_specifics` / `all_variants` instead. */
    variants?: AgentProductDetailsResponse.Variants.Item[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace AgentProductDetailsResponse {
    /** `completed` when the payload below is populated. `processing` when `async=true` was passed and the fetch is still running — poll again. `failed` when the retailer returned an error; see `code` and `message`. */
    export const Status = {
        Completed: "completed",
        Processing: "processing",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type VariantSpecifics = VariantSpecifics.Item[];

    export namespace VariantSpecifics {
        export interface Item {
            /** Variant axis, e.g. `Color` or `Size`. */
            dimension?: string | undefined;
            /** Value on that axis, e.g. `Black` or `Large`. */
            value?: string | undefined;
        }
    }

    export type AllVariants = AllVariants.Item[];

    export namespace AllVariants {
        export interface Item {
            /** Identifier of that variant. */
            product_id?: string | undefined;
            /** Axis/value pairs for that variant. */
            variant_specifics?: Item.VariantSpecifics.Item[] | undefined;
        }

        export namespace Item {
            export type VariantSpecifics = VariantSpecifics.Item[];

            export namespace VariantSpecifics {
                export interface Item {
                    /** Variant axis, e.g. `Color` or `Size`. */
                    dimension?: string | undefined;
                    /** Value on that axis, e.g. `Black` or `Large`. */
                    value?: string | undefined;
                }
            }
        }
    }

    export type Epids = Epids.Item[];

    export namespace Epids {
        export interface Item {
            /** Identifier type: `UPC`, `EAN`, `MPN`, … */
            type?: string | undefined;
            /** Identifier value. */
            value?: string | undefined;
        }
    }

    /**
     * Amazon only. Shipping weight and package size.
     */
    export interface PackageDimensions {
        weight?: PackageDimensions.Weight | undefined;
        size?: PackageDimensions.Size | undefined;
    }

    export namespace PackageDimensions {
        export interface Weight {
            /** Numeric amount. */
            amount?: number | undefined;
            /** Unit, e.g. `inches`, `ounces`, `pounds`. */
            unit?: string | undefined;
        }

        export interface Size {
            width?: Size.Width | undefined;
            depth?: Size.Depth | undefined;
            length?: Size.Length | undefined;
        }

        export namespace Size {
            export interface Width {
                /** Numeric amount. */
                amount?: number | undefined;
                /** Unit, e.g. `inches`, `ounces`, `pounds`. */
                unit?: string | undefined;
            }

            export interface Depth {
                /** Numeric amount. */
                amount?: number | undefined;
                /** Unit, e.g. `inches`, `ounces`, `pounds`. */
                unit?: string | undefined;
            }

            export interface Length {
                /** Numeric amount. */
                amount?: number | undefined;
                /** Unit, e.g. `inches`, `ounces`, `pounds`. */
                unit?: string | undefined;
            }
        }
    }

    export type Offers = Offers.Item[];

    export namespace Offers {
        export interface Item {
            /** Best Buy's own label: `New`, `Open-Box Excellent`, … */
            condition?: (string | null) | undefined;
            /** Price in cents for this condition. */
            price?: number | undefined;
            /** `InStock`, `OutOfStock`, `PreOrder`, … */
            availability?: (string | null) | undefined;
            /** Whether this is the new-condition offer. */
            "new"?: boolean | undefined;
            /** Seller name. */
            seller?: (string | null) | undefined;
        }
    }

    export type Variants = Variants.Item[];

    export namespace Variants {
        export interface Item {
            /** Variant id. Shopify: pass it when ordering to pick this variant. */
            variant_id?: (string | null) | undefined;
            /** Shopify only. Variant title, e.g. `Black / Large`. */
            title?: (string | null) | undefined;
            /** Merchant SKU. */
            sku?: (string | null) | undefined;
            /** Price in cents (minor units of `currency_code` on Etsy). */
            price?: (number | null) | undefined;
            /** Etsy only. Currency of `price`. */
            currency_code?: (string | null) | undefined;
            /** Etsy only. Units in stock. */
            quantity?: (number | null) | undefined;
            /** Whether this variant can be bought. */
            available?: (boolean | null) | undefined;
            /** Etsy only. Axis/value pairs that identify this variant. */
            properties?: Item.Properties.Item[] | undefined;
        }

        export namespace Item {
            export type Properties = Properties.Item[];

            export namespace Properties {
                export interface Item {
                    /** Axis, e.g. `Color`. */
                    name?: (string | null) | undefined;
                    /** Value, e.g. `Blue`. */
                    value?: (string | null) | undefined;
                }
            }
        }
    }
}
