// This file was auto-generated by Fern from our API Definition.

export interface AgentProductOffersResponse {
    status: AgentProductOffersResponse.Status;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace AgentProductOffersResponse {
    export const Status = {
        Completed: "completed",
        Processing: "processing",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
