// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Zinc from "../../../index.js";

export declare namespace ReturnsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ReturnsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ReturnsClient.Options>;

    constructor(options: ReturnsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Zinc.ListReturnRequestsReturnsGetRequest} request
     * @param {ReturnsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zinc.UnprocessableEntityError}
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.returns.listReturnRequests()
     */
    public listReturnRequests(
        request: Zinc.ListReturnRequestsReturnsGetRequest = {},
        requestOptions?: ReturnsClient.RequestOptions,
    ): core.HttpResponsePromise<Zinc.ReturnRequestListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listReturnRequests(request, requestOptions));
    }

    private async __listReturnRequests(
        request: Zinc.ListReturnRequestsReturnsGetRequest = {},
        requestOptions?: ReturnsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zinc.ReturnRequestListResponse>> {
        const { limit, offset, search, status, authorization } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            search,
            status,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ authorization: authorization ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                "returns",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Zinc.ReturnRequestListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Zinc.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZincError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/returns");
    }

    /**
     * @param {Zinc.ReturnRequestCreate} request
     * @param {ReturnsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zinc.ConflictError}
     * @throws {@link Zinc.UnprocessableEntityError}
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.returns.createReturnRequest({
     *         order_id: "order_id",
     *         items: [{
     *                 order_item_id: "order_item_id",
     *                 quantity: 1
     *             }],
     *         reason: "damaged"
     *     })
     */
    public createReturnRequest(
        request: Zinc.ReturnRequestCreate,
        requestOptions?: ReturnsClient.RequestOptions,
    ): core.HttpResponsePromise<Zinc.ReturnRequestResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createReturnRequest(request, requestOptions));
    }

    private async __createReturnRequest(
        request: Zinc.ReturnRequestCreate,
        requestOptions?: ReturnsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zinc.ReturnRequestResponse>> {
        const { authorization, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ authorization: authorization ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                "returns",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Zinc.ReturnRequestResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 409:
                    throw new Zinc.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Zinc.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZincError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/returns");
    }

    /**
     * @param {Zinc.GetReturnRequestReturnsReturnRequestIdGetRequest} request
     * @param {ReturnsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zinc.UnprocessableEntityError}
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.returns.getReturnRequest({
     *         return_request_id: "return_request_id"
     *     })
     */
    public getReturnRequest(
        request: Zinc.GetReturnRequestReturnsReturnRequestIdGetRequest,
        requestOptions?: ReturnsClient.RequestOptions,
    ): core.HttpResponsePromise<Zinc.ReturnRequestResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getReturnRequest(request, requestOptions));
    }

    private async __getReturnRequest(
        request: Zinc.GetReturnRequestReturnsReturnRequestIdGetRequest,
        requestOptions?: ReturnsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zinc.ReturnRequestResponse>> {
        const { return_request_id: returnRequestId, authorization } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ authorization: authorization ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                `returns/${core.url.encodePathParam(returnRequestId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Zinc.ReturnRequestResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Zinc.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZincError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/returns/{return_request_id}");
    }
}
