// This file was auto-generated by Fern from our API Definition.

import * as errors from "./index.js";

export class ZincTimeoutError extends errors.ZincError {
    constructor(message: string, opts?: { cause?: unknown }) {
        super({
            message: message,
            cause: opts?.cause,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "ZincTimeoutError";
    }
}
