// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         short_id: "short_id"
 *     }
 */
export interface DeleteRetailerCredentialsManagedAccountsShortIdDeleteRequest {
    short_id: string;
    authorization?: string | null;
}
