// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListRetailerCredentialsManagedAccountsGetRequest {
    /** Page size (default 50, max 500). Responses include `total` for paging past it. */
    limit?: number;
    /** Number of credentials to skip */
    offset?: number;
    /** Partial match on email or retailer */
    search?: string | null;
    authorization?: string | null;
}
