// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetMyUsageUsageGetRequest {
    /** Trailing window in days (max 90). */
    window_days?: number;
    /** How many recent calls to return. */
    recent?: number;
    authorization?: string | null;
}
