// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Zinc from "../../../index.js";

export declare namespace SearchClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SearchClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SearchClient.Options>;

    constructor(options: SearchClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Search for products across retailers; returns orderable zn_sku_ listings.
     *
     * **Billing.** This is a metered data call: $0.01 is drawn from your wallet per successful request, before any order is placed. An empty wallet gets `402` instead. Sandbox (`zn_test_`) calls are free and never touch the live wallet.
     *
     * @param {Zinc.SearchSearchGetRequest} request
     * @param {SearchClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zinc.PaymentRequiredError}
     * @throws {@link Zinc.UnprocessableEntityError}
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.search.search({
     *         q: "q"
     *     })
     */
    public search(
        request: Zinc.SearchSearchGetRequest,
        requestOptions?: SearchClient.RequestOptions,
    ): core.HttpResponsePromise<Zinc.SearchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__search(request, requestOptions));
    }

    private async __search(
        request: Zinc.SearchSearchGetRequest,
        requestOptions?: SearchClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zinc.SearchResponse>> {
        const { q, min_price: minPrice, max_price: maxPrice, authorization } = request;
        const _queryParams: Record<string, unknown> = {
            q,
            min_price: minPrice,
            max_price: maxPrice,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ authorization: authorization ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                "search",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Zinc.SearchResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 402:
                    throw new Zinc.PaymentRequiredError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Zinc.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZincError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/search");
    }
}
