// This file was auto-generated by Fern from our API Definition.

/**
 * Shipping address model.
 *
 * Supports international addresses. The `state` field is optional for countries
 * that don't use states/provinces. The `country` field uses ISO 3166-1 alpha-2
 * country codes (e.g., "US", "CA", "GB", "DE").
 */
export interface Address {
    first_name: string;
    last_name: string;
    address_line1: string;
    address_line2?: (string | null) | undefined;
    city: string;
    state?: (string | null) | undefined;
    postal_code: string;
    phone_number: string;
    country?: string | undefined;
}
