// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * The issued key, plus what the agent needs to act on it right away.
 */
export interface ApiKeyExchangeResponse {
    id: string;
    key: string;
    name: string | null;
    is_active: boolean;
    is_test: boolean;
    created_at: string;
    /** Spendable wallet balance of the account the key belongs to. */
    wallet_balance_cents: number;
    /** What the sandbox claim moved, when `sandbox_key` was sent. */
    sandbox?: (Zinc.SandboxClaimSummary | null) | undefined;
    /** Wallet credit granted alongside this key, if the account earned one, with a few items it is known to cover. */
    starter_credit?: (Zinc.StarterCredit | null) | undefined;
    api_key?: string | undefined;
}
