// This file was auto-generated by Fern from our API Definition.

/**
 * Raw CSV rows (header -> cell) posted from the dashboard.
 */
export interface BulkUploadRequest {
    /** Original uploaded filename, for display. */
    filename?: (string | null) | undefined;
    /** Parsed CSV rows, each a mapping of column header to cell value. */
    rows?: Record<string, unknown>[] | undefined;
}
