// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * A user's recent bulk-upload batches (newest first).
 */
export interface BulkBatchListResponse {
    batches?: Zinc.BulkBatchResponse[] | undefined;
    total: number;
}
