// This file was auto-generated by Fern from our API Definition.

/** Lifecycle of a CSV bulk-upload batch. */
export const BulkBatchStatus = {
    Pending: "pending",
    Processing: "processing",
    Completed: "completed",
    Failed: "failed",
} as const;
export type BulkBatchStatus = (typeof BulkBatchStatus)[keyof typeof BulkBatchStatus];
