// This file was auto-generated by Fern from our API Definition.

/**
 * Per-row result of a dry-run validation.
 */
export interface BulkRowValidation {
    /** Zero-based row index in the uploaded file. */
    index: number;
    ok: boolean;
    errors?: string[] | undefined;
    product_urls?: string[] | undefined;
    quantities?: number[] | undefined;
    recipient?: (string | null) | undefined;
    destination?: (string | null) | undefined;
    max_price?: (number | null) | undefined;
    retailer_credentials_id?: (string | null) | undefined;
    passthrough?: Record<string, unknown> | undefined;
}
