// This file was auto-generated by Fern from our API Definition.

export interface Components {
    db: Components.Db;
    queue: Components.Queue;
    ordering: Components.Ordering;
}

export namespace Components {
    export const Db = {
        Up: "up",
        Warning: "warning",
        Down: "down",
    } as const;
    export type Db = (typeof Db)[keyof typeof Db];
    export const Queue = {
        Up: "up",
        Warning: "warning",
        Down: "down",
    } as const;
    export type Queue = (typeof Queue)[keyof typeof Queue];
    export const Ordering = {
        Up: "up",
        Warning: "warning",
        Down: "down",
    } as const;
    export type Ordering = (typeof Ordering)[keyof typeof Ordering];
}
