// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * What the catalog does and does not tell you.
 *
 * Sits on `GET /retailers` because that list reads as the whole answer and is
 * not: it is the curated set, while the order path accepts most stores.
 */
export interface CoverageInfo {
    /** 'open': listed retailers are not the limit. */
    policy: string;
    summary: string;
    platforms?: Zinc.CoveragePlatform[] | undefined;
}
