// This file was auto-generated by Fern from our API Definition.

/**
 * End-customer email-notification status for an order.
 *
 * Present only when the order opted into the notifications add-on. ``delivered``
 * is the deliverability signal: True once a notification reached the shopper
 * (an unsubscribe click also counts — it proves receipt), False if one was
 * attempted but bounced/failed/suppressed, and null while nothing has been
 * sent yet (e.g. not shipped) or a send is still in flight.
 */
export interface CustomerNotificationStatus {
    email: string;
    delivered?: (boolean | null) | undefined;
}
