// This file was auto-generated by Fern from our API Definition.

/**
 * Opt-in to email the END customer as this order progresses.
 *
 * Providing this block opts the order into the notifications add-on: a
 * per-order surcharge is applied and the public tracking page becomes
 * reachable for the order. The feature is gated server-side by
 * ``customer_emails_enabled``; while that's off the block has no effect.
 */
export interface CustomerNotifications {
    /** End-customer email address to send order updates to. */
    email: string;
}
