// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Recent delivered orders as deduplicated, anonymized map points.
 */
export interface DeliveryMapResponse {
    points: Zinc.DeliveryMapPoint[];
    window_days: number;
    generated_at: string;
}
