// This file was auto-generated by Fern from our API Definition.

/**
 * One delivered-order marker for the marketing site's globe.
 *
 * Coordinates are a ZIP centroid rounded to two decimals — never a street
 * address, but the rounding does not hide which ZIP (see
 * ``lib.routers.stats``). Deliberately carries no order id, name, address,
 * or per-point timestamp.
 */
export interface DeliveryMapPoint {
    lat: number;
    long: number;
    emoji: string;
}
