// This file was auto-generated by Fern from our API Definition.

/**
 * What the approval page shows before the human decides. Public: it holds
 * only what the agent chose to say about itself.
 */
export interface DeviceCodeInfo {
    user_code: string;
    name: string;
    /** Runtime guessed from the requesting User-Agent (claude-code, codex, curl, …). */
    source: string;
    /** Approval will also claim the agent's sandbox into the approving account. */
    sandbox_attached: boolean;
    /** Wallet credit approval would add, when the attached sandbox has placed an order and the account has not had one; null otherwise. */
    starter_credit_cents?: (number | null) | undefined;
    /** pending | approved | denied */
    status: string;
}
