// This file was auto-generated by Fern from our API Definition.

export interface DeviceCodeCreate {
    /** What to call yourself on the approval screen and as the key's label, e.g. 'Claude Code' or 'acme-restock-agent'. */
    name?: (string | null) | undefined;
}
