// This file was auto-generated by Fern from our API Definition.

export interface DeviceCodeResponse {
    /** Your half of the handshake. Keep it; send it when polling. Never show it to the human. */
    device_code: string;
    /** The short code the human sees on the approval page. */
    user_code: string;
    /** Where the human approves; they will be asked for `user_code`. */
    verification_uri: string;
    /** Same page with the code filled in. Show this one. */
    verification_uri_complete: string;
    /** Seconds until this code stops working. */
    expires_in: number;
    /** Minimum seconds between polls of POST /device/token. */
    interval: number;
    /** One sentence to show your operator, ready to paste. */
    human_message: string;
    /** What to do now. */
    next: string;
}
