// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Structured detail for a failed job.
 *
 * Additive sibling to the flat `error`/`error_type` keys (kept for
 * back-compat). The structured home for enrichment beyond the category +
 * message — e.g. why a shipping address was rejected — so we don't keep
 * growing loose top-level keys on the job output.
 */
export interface ErrorDetails {
    code: string;
    message: string;
    url?: (string | null) | undefined;
    address_validation_reasons?: string[] | undefined;
    field_errors?: Zinc.FieldError[] | undefined;
    line_rejections?: Zinc.LineRejection[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
