// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Standard error response body.
 */
export interface ErrorDetail {
    code: Zinc.ErrorCode;
    message: string;
    details?: (Record<string, unknown> | null) | undefined;
}
