// This file was auto-generated by Fern from our API Definition.

/**
 * A single field-level validation failure from a worker.
 *
 * Mirrors Sonic's `FieldError` (src/agent/types.py): when a job fails schema
 * validation the worker reports one of these per offending field, so consumers
 * can show "state should be 'NY', got 'New York'" instead of a bare count.
 */
export interface FieldError {
    field: string;
    code: string;
    message?: string | undefined;
    received?: unknown | undefined;
    expected?: (string | null) | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
