// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Which strict order rules may be relaxed. The order contract is strict by
 * default; this object only ever loosens it.
 *
 * One key per concern — ``gift``, ``items``, ``quantity`` — whose value is the
 * mode to hold that rule at. Absent (or null) is today's behaviour, so an
 * omitted block and ``{}`` mean the same strict order. There is deliberately
 * no ``"strict"`` mode to write — the existing fields already mean that
 * (``is_gift: true`` is a required gift; a products list is all-or-nothing),
 * and a second spelling of the same intent is a second thing to get wrong.
 * Unknown keys and unknown modes are rejected rather than ignored, so a typo
 * can never silently mean "strict".
 *
 * Extension point: a softer mode for a concern is a new ``FulfillmentMode``
 * member (``prefer``, ``nearest``); a per-concern knob is that concern's value
 * widening from a bare mode into an object (``items: {mode: "best_effort",
 * min_items: 2}``) — never a new top-level order field.
 */
export interface FulfillmentPreferences {
    /** `best_effort`: if the retailer offers no free gift option, place a normal order instead of failing with `gift_option_unavailable`. Requires `is_gift: true`. Omit to keep the gift requirement strict. */
    gift?: (Zinc.FulfillmentMode | null) | undefined;
    /** `best_effort`: if an item can't be bought (not found, out of stock, variant or condition unavailable, add-to-cart failed), skip it and ship the rest — its status becomes `skipped`. An empty cart still fails. Omit for all-or-nothing. */
    items?: (Zinc.FulfillmentMode | null) | undefined;
    /** `best_effort`: if the retailer caps an item below the requested quantity, buy the cap instead of failing with `quantity_limit_exceeded`. Omit to require the full quantity. */
    quantity?: (Zinc.FulfillmentMode | null) | undefined;
}
