// This file was auto-generated by Fern from our API Definition.

/**
 * One rule that was actually relaxed while placing the order.
 */
export interface FulfillmentConcession {
    concern: FulfillmentConcession.Concern;
    /** Worker error code that would have failed a strict order. */
    code: string;
    message?: (string | null) | undefined;
    /** Order item this concession is about, if any. */
    item_id?: (string | null) | undefined;
    url?: (string | null) | undefined;
    requested_quantity?: (number | null) | undefined;
    fulfilled_quantity?: (number | null) | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace FulfillmentConcession {
    export const Concern = {
        Gift: "gift",
        Items: "items",
        Quantity: "quantity",
    } as const;
    export type Concern = (typeof Concern)[keyof typeof Concern];
}
