// This file was auto-generated by Fern from our API Definition.

/**
 * How hard to hold one order rule — the value of a ``fulfillment`` key
 * (``fulfillment.items: "best_effort"``).
 *
 * Every mode loosens; strict is the *absence* of a mode, never a spelling of
 * one. A future softer mode for a concern (``prefer``, ``nearest``) is a new
 * member here; a future per-concern knob is that concern's value growing from
 * a bare mode into an object — neither is a new top-level order field.
 */
export const FulfillmentMode = {
    BestEffort: "best_effort",
} as const;
export type FulfillmentMode = (typeof FulfillmentMode)[keyof typeof FulfillmentMode];
