// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Zinc's all-time order and GMV totals.
 *
 * Top-level ``orders_successful`` / ``gmv_cents`` are the v2 (this service's)
 * numbers, live as of ``v2_as_of``; ``v1`` is the seeded legacy snapshot;
 * ``combined`` is the convenience sum of both.
 */
export interface LifetimeStatsResponse {
    orders_successful: number;
    gmv_cents: number;
    v2_as_of: string;
    v1: Zinc.LifetimeV1Stats;
    combined: Zinc.LifetimeTotals;
}
