// This file was auto-generated by Fern from our API Definition.

/**
 * All-time totals from the legacy v1 API (api.zinc.io).
 *
 * ``source: "computed"`` — read from the snapshot the weekly worker job
 * stores (see ``lib.tasks.v1_lifetime``); ``source: "seeded"`` — the
 * in-code cold-start fallback constant.
 */
export interface LifetimeV1Stats {
    orders_successful: number;
    gmv_cents: number;
    as_of: string;
    source?: LifetimeV1Stats.Source | undefined;
}

export namespace LifetimeV1Stats {
    export const Source = {
        Seeded: "seeded",
        Computed: "computed",
    } as const;
    export type Source = (typeof Source)[keyof typeof Source];
}
