// This file was auto-generated by Fern from our API Definition.

/**
 * Combined v1 + v2 all-time totals.
 */
export interface LifetimeTotals {
    orders_successful: number;
    gmv_cents: number;
}
