// This file was auto-generated by Fern from our API Definition.

/**
 * One order line the retailer rejected, as it reported it (BizAPI).
 */
export interface LineRejection {
    url?: (string | null) | undefined;
    product_id?: (string | null) | undefined;
    requested_quantity?: (number | null) | undefined;
    available_quantity?: (number | null) | undefined;
    codes?: string[] | undefined;
    messages?: string[] | undefined;
}
