// This file was auto-generated by Fern from our API Definition.

/**
 * Customer's markup on the order cost (computed before fees).
 */
export interface MarginSpec {
    type: MarginSpec.Type;
    /** Cents when type='flat'; a percentage when type='percent' (e.g. 15 == 15%). */
    value: number;
}

export namespace MarginSpec {
    export const Type = {
        Flat: "flat",
        Percent: "percent",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
