// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * List of orders for a particular user_id
 */
export interface OrderListResponse {
    orders: Zinc.OrderResponse[];
    total: number;
    limit: number;
    offset: number;
}
