// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Customer-facing lifecycle timeline for an order.
 *
 * Derived on read by merging placement logs (OrderLog) with carrier tracking
 * state (TrackingNumber / TrackingCheckpoint). No dedicated storage — works
 * retroactively on every historical order.
 */
export interface OrderTimelineResponse {
    order_id: string;
    current_status: Zinc.OrderStatus;
    milestones: Zinc.OrderMilestone[];
}
