// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Request model for creating a new order.
 */
export interface OrderCreate {
    products: Zinc.OrderProduct[];
    shipping_address: Zinc.Address;
    /** Maximum price (in cents) allowed for an order before it is finalized. */
    max_price: number;
    /** Optional idempotency key to prevent duplicate orders. If not provided, one will be generated. */
    idempotency_key?: (string | null) | undefined;
    /** Optional short ID (e.g., 'zn_acct_XXXXXXXX') of specific retailer credentials to use for this order. If not provided, credentials will be selected automatically. */
    retailer_credentials_id?: (string | null) | undefined;
    /** Optional metadata to attach to the order. Can contain arbitrary key-value pairs. */
    metadata?: (Record<string, unknown> | null) | undefined;
    /** Optional purchase order number for the order. */
    po_number?: (string | null) | undefined;
    /** Optional ceiling on a seller's shipping and handling days. Omit or send null for no limit. */
    handling_days_max?: (number | null) | undefined;
    /** Mark the order as a gift. Prices are suppressed on the packing slip where the fulfillment method supports it. */
    is_gift?: boolean | undefined;
    /** Optional payment block. Omit for prepaid-wallet billing (default). */
    payment?: (Zinc.OrderPayment | null) | undefined;
}
