// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Response model for order data.
 */
export interface OrderResponse {
    id: string;
    status: Zinc.OrderStatus;
    max_price: number;
    attempts: number;
    items: Zinc.OrderItemResponse[];
    shipping_address: Record<string, unknown>;
    metadata?: Record<string, unknown> | undefined;
    po_number?: (string | null) | undefined;
    handling_days_max?: (number | null) | undefined;
    is_gift?: boolean | undefined;
    gift_message?: (string | null) | undefined;
    retailer_credentials_id: string | null;
    retailer_credentials_uuid?: (string | null) | undefined;
    /** Fulfillment result and price breakdown for a completed or failed order; null while processing. */
    job_result?: (Zinc.OrderJobResult | null) | undefined;
    /** The retailer's own order number(s) for this order (e.g. an Amazon `113-…` ID), as recorded when it was placed. Empty while processing, or if the order never reached the retailer. */
    merchant_order_ids?: string[] | undefined;
    tracking_numbers?: Zinc.TrackingNumberResponse[] | undefined;
    created_by?: (string | null) | undefined;
    user_id?: (number | null) | undefined;
    returns?: Zinc.ReturnRequestSummary[] | undefined;
    /** Stripe Connect charge details when this order was paid via Connect; null for prepaid-wallet orders. */
    connect?: (Zinc.OrderConnectInfo | null) | undefined;
    /** Card hold details when this order was paid with payment.mode='card'; null for wallet and Connect orders. */
    payment?: (Zinc.OrderPaymentInfo | null) | undefined;
    /** End-customer email-notification status when the order opted into the notifications add-on; null when it didn't. */
    customer_notifications?: (Zinc.CustomerNotificationStatus | null) | undefined;
    /** `gift`/`items`/`quantity`: the mode this order asked for on each rule (all null = strict). `concessions`: every rule that actually was relaxed, with the worker's code and the item it concerned. Empty concessions means the order was fulfilled exactly as requested. */
    fulfillment?: Zinc.OrderFulfillment | undefined;
    created_at: string;
    updated_at: string;
}
