// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Response model for order data.
 */
export interface OrderResponse {
    id: string;
    status: Zinc.OrderStatus;
    max_price: number;
    attempts: number;
    items: Zinc.OrderItemResponse[];
    shipping_address: Record<string, unknown>;
    metadata?: Record<string, unknown> | undefined;
    po_number?: (string | null) | undefined;
    handling_days_max?: (number | null) | undefined;
    is_gift?: boolean | undefined;
    retailer_credentials_id: string | null;
    retailer_credentials_uuid?: (string | null) | undefined;
    /** Fulfillment result and price breakdown for a completed or failed order; null while processing. */
    job_result?: (Zinc.OrderJobResult | null) | undefined;
    tracking_numbers?: Zinc.TrackingNumberResponse[] | undefined;
    created_by?: (string | null) | undefined;
    user_id?: (number | null) | undefined;
    returns?: Zinc.ReturnRequestSummary[] | undefined;
    /** Stripe Connect charge details when this order was paid via Connect; null for prepaid-wallet orders. */
    connect?: (Zinc.OrderConnectInfo | null) | undefined;
    created_at: string;
    updated_at: string;
}
