// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Retailer price breakdown for an order, all amounts in cents.
 *
 * Lenient by design — every field is optional and unknown keys are preserved
 * (``extra="allow"``) — because it mirrors fulfillment output that may be
 * partial (e.g. a failed order) or carry extra detail. Documents the common
 * fields without revalidating the raw payload.
 */
export interface OrderPriceComponents {
    subtotal?: (number | null) | undefined;
    tax?: (number | null) | undefined;
    shipping?: (number | null) | undefined;
    /** Promotion/free-shipping discount applied by the retailer, as a positive magnitude subtracted from the total. A nonzero `shipping` paired with an equal `discount` means shipping was itemized but waived — the total correctly excludes it. */
    discount?: (number | null) | undefined;
    /** Retailer fees not folded into subtotal/shipping/tax (gift wrap, import/regulatory charges), as a positive magnitude added to the total. Surfaced so a total exceeding the shown parts reads as an itemized fee rather than an unexplained charge. */
    fees?: (number | null) | undefined;
    /** Order total in `currency` (subtotal + tax + shipping + fees − discount). */
    total?: (number | null) | undefined;
    /** `total` converted to the currency actually charged. */
    converted_payment_total?: (number | null) | undefined;
    currency?: (string | null) | undefined;
    payment_currency?: (string | null) | undefined;
    /** Per-product rows making up `subtotal`. Distinct from `line_items`, which carries order-level adjustments (discounts, fees) and shares no fields with these — a discount is never a cart row. Null when the retailer's checkout page did not expose readable line items, so handle both `null` and `[]`. Individual fields may also be null on a row we could only partly read. Best-effort: `sum(line_total)` normally equals `subtotal`, but that is not guaranteed and must not be used as a billing input — the charge is always driven by `total`. */
    cart_items?: (Zinc.OrderCartItem[] | null) | undefined;
    /** Order-level adjustments, each `{description, amount, category}`. Null — not `[]` — when the producer didn't supply them, which is every BizAPI-placed order today, so null-check before iterating. */
    line_items?: (Record<string, unknown>[] | null) | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
