// This file was auto-generated by Fern from our API Definition.

export const OrderItemStatus = {
    Pending: "pending",
    Processing: "processing",
    Ordered: "ordered",
    Shipped: "shipped",
    Delivered: "delivered",
    Cancelled: "cancelled",
    Failed: "failed",
    Skipped: "skipped",
} as const;
export type OrderItemStatus = (typeof OrderItemStatus)[keyof typeof OrderItemStatus];
