// This file was auto-generated by Fern from our API Definition.

/**
 * Stripe Connect charge + state for an order paid via Connect. Present only
 * when the order has a Connect profile; ``null`` for prepaid-wallet orders. All
 * amounts in cents.
 *
 * ``state`` moves ``secured`` → ``captured`` (or ``released``/``refunded`` on a
 * terminal outcome). The post-capture fields (``order_cost`` and below) are
 * populated once Zinc places the order with the retailer and the actual total
 * is captured.
 */
export interface OrderConnectInfo {
    /** secured | captured | released | refunded | … */
    state: string;
    secured_amount?: (number | null) | undefined;
    /** Actual order cost (goods) captured when the order is placed. */
    order_cost?: (number | null) | undefined;
    customer_margin?: (number | null) | undefined;
    zinc_fee?: (number | null) | undefined;
    stripe_fee?: (number | null) | undefined;
    final_charge?: (number | null) | undefined;
    transfer_amount?: (number | null) | undefined;
    payment_intent_id?: (string | null) | undefined;
    connected_account_id?: (string | null) | undefined;
    simulated?: boolean | undefined;
}
