// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * What was asked (the per-concern modes, all null on a strict order) plus
 * what was actually relaxed (``concessions``, empty when the order was
 * fulfilled exactly as requested — which is every strict order).
 */
export interface OrderFulfillment {
    /** `best_effort`: if the retailer offers no free gift option, place a normal order instead of failing with `gift_option_unavailable`. Requires `is_gift: true`. Omit to keep the gift requirement strict. */
    gift?: (Zinc.FulfillmentMode | null) | undefined;
    /** `best_effort`: if an item can't be bought (not found, out of stock, variant or condition unavailable, add-to-cart failed), skip it and ship the rest — its status becomes `skipped`. An empty cart still fails. Omit for all-or-nothing. */
    items?: (Zinc.FulfillmentMode | null) | undefined;
    /** `best_effort`: if the retailer caps an item below the requested quantity, buy the cap instead of failing with `quantity_limit_exceeded`. Omit to require the full quantity. */
    quantity?: (Zinc.FulfillmentMode | null) | undefined;
    concessions?: Zinc.FulfillmentConcession[] | undefined;
}
