// This file was auto-generated by Fern from our API Definition.

/**
 * Retailer price breakdown for an order, all amounts in cents.
 *
 * Lenient by design — every field is optional and unknown keys are preserved
 * (``extra="allow"``) — because it mirrors fulfillment output that may be
 * partial (e.g. a failed order) or carry extra detail. Documents the common
 * fields without revalidating the raw payload.
 */
export interface OrderPriceComponents {
    subtotal?: (number | null) | undefined;
    tax?: (number | null) | undefined;
    shipping?: (number | null) | undefined;
    /** Promotion/free-shipping discount applied by the retailer, as a positive magnitude subtracted from the total. A nonzero `shipping` paired with an equal `discount` means shipping was itemized but waived — the total correctly excludes it. */
    discount?: (number | null) | undefined;
    /** Retailer fees not folded into subtotal/shipping/tax (gift wrap, import/regulatory charges), as a positive magnitude added to the total. Surfaced so a total exceeding the shown parts reads as an itemized fee rather than an unexplained charge. */
    fees?: (number | null) | undefined;
    /** Order total in `currency` (subtotal + tax + shipping + fees − discount). */
    total?: (number | null) | undefined;
    /** `total` converted to the currency actually charged. */
    converted_payment_total?: (number | null) | undefined;
    currency?: (string | null) | undefined;
    payment_currency?: (string | null) | undefined;
    /** Itemized rows, each `{description, amount, category}`. */
    line_items?: (Record<string, unknown>[] | null) | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
