// This file was auto-generated by Fern from our API Definition.

export const OrderStatus = {
    Pending: "pending",
    InProgress: "in_progress",
    OrderPlaced: "order_placed",
    OrderFailed: "order_failed",
    Cancelled: "cancelled",
    CancelledByRetailer: "cancelled_by_retailer",
} as const;
export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];
