// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Optional payment block. Absent or mode='wallet' ⇒ unchanged prepaid-wallet
 * behavior. mode='connect' charges the end-customer's vaulted card in real time
 * via Stripe Connect (see ConnectService).
 */
export interface OrderPayment {
    mode?: OrderPayment.Mode | undefined;
    /** Connect mode: the end-customer's vaulted Stripe payment-method id on the customer's connected account. */
    payment_method?: (string | null) | undefined;
    /** Connect mode: the end-customer's Stripe Customer id (cus_…) on the connected account. Required to charge a *reusable* saved card off-session; omit only for a one-time, unattached payment method. */
    customer?: (string | null) | undefined;
    /** Connect mode: the customer's margin on the order. */
    margin?: (Zinc.MarginSpec | null) | undefined;
}

export namespace OrderPayment {
    export const Mode = {
        Wallet: "wallet",
        Connect: "connect",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
