// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Fulfillment result surfaced on a completed or failed order. Null while the
 * order is still processing.
 *
 * Lenient and open (``extra="allow"``) so it documents the common fields —
 * success, price breakdown, errors, merchant order ids, delivery estimate —
 * without constraining the full processing payload, which carries additional
 * internal detail.
 */
export interface OrderJobResult {
    success?: (boolean | null) | undefined;
    error?: (string | null) | undefined;
    error_type?: (string | null) | undefined;
    error_details?: (Zinc.ErrorDetails | null) | undefined;
    price_components?: (Zinc.OrderPriceComponents | null) | undefined;
    estimated_delivery?: (string | null) | undefined;
    merchant_order_ids?: (Record<string, unknown>[] | null) | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
