// This file was auto-generated by Fern from our API Definition.

/**
 * What the hold covers. All amounts in cents.
 */
export interface PaymentQuote {
    /** The order's spending cap. */
    max_price_cents: number;
    /** Zinc's per-order fee. */
    order_fee_cents: number;
    /** Stripe's processing cut, grossed into hold_cents so the order fee is what Zinc actually nets. */
    stripe_fee_cents?: number | undefined;
    /** Authorized on the card: max_price + fee + processing. Only the actual retailer total plus those is captured; the rest is released. */
    hold_cents: number;
}
