// This file was auto-generated by Fern from our API Definition.

/**
 * The assistant the buyer came from, so the payment page can send them
 * back once the order is placed.
 */
export interface PendingPaymentClient {
    /** Display name, e.g. 'Claude'. */
    name: string;
    /** Where 'back' goes when the tab cannot close itself; null when the client has no web home we know of. */
    url?: (string | null) | undefined;
}
