// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * A card payment the buyer still has to complete, or just did.
 */
export interface PendingPaymentResponse {
    id: string;
    status: PendingPaymentResponse.Status;
    /** Set once the order exists (status 'placed'). */
    order_id?: (string | null) | undefined;
    /** Where the buyer pays: the Stripe Checkout page for this payment (or Zinc's hosted page, which opens it, if Stripe could not be reached when the order was posted). Null once the payment no longer needs the buyer. */
    pay_url?: (string | null) | undefined;
    expires_at: string;
    quote: Zinc.PaymentQuote;
    products: Zinc.PendingPaymentProduct[];
    /** Set when the caller said which assistant the buyer is using (X-Zinc-Client on POST /orders). */
    client?: (Zinc.PendingPaymentClient | null) | undefined;
    /** Recipient, city, state and postcode — enough for the payment page to show what is being bought without exposing the full address. */
    ship_to_summary: string;
}

export namespace PendingPaymentResponse {
    export const Status = {
        RequiresAction: "requires_action",
        Authorized: "authorized",
        Placed: "placed",
        Expired: "expired",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
