// This file was auto-generated by Fern from our API Definition.

/**
 * Product variant schema for selecting product options (color, size, etc.).
 */
export interface ProductVariant {
    /** Variant label (e.g., 'Color', 'Size') */
    label: string;
    /** Variant value (e.g., 'Black', 'Large') */
    value: string;
}
