// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Response from the product search endpoint.
 */
export interface ProductSearchResponse {
    status: string;
    results?: Zinc.ProductSearchResult[] | undefined;
    /** Only set on free_shipping searches: the page to request to keep paging. An empty `results` with a non-null next_page is NOT the end of results — request next_page to continue. None means results are exhausted (or the search was unfiltered). */
    next_page?: (number | null) | undefined;
}
