// This file was auto-generated by Fern from our API Definition.

/**
 * Normalized product search result across retailers.
 *
 * Common fields are required or have defaults; retailer-specific fields are optional.
 */
export interface ProductSearchResult {
    product_id: string;
    title: string;
    image?: (string | null) | undefined;
    brand?: (string | null) | undefined;
    price?: (number | null) | undefined;
    stars?: (number | null) | undefined;
    num_reviews?: (number | null) | undefined;
    num_offers_estimate?: (number | null) | undefined;
    num_sales?: (number | null) | undefined;
    product_details?: (unknown[] | null) | undefined;
    fresh?: (boolean | null) | undefined;
    prime?: (boolean | null) | undefined;
    pantry?: (boolean | null) | undefined;
    addon?: (boolean | null) | undefined;
    ship_price?: (number | null) | undefined;
    upc?: (string | null) | undefined;
    mpn?: (string | null) | undefined;
    available?: (boolean | null) | undefined;
    available_online?: (boolean | null) | undefined;
    available_instore?: (boolean | null) | undefined;
    freight_shipping?: (boolean | null) | undefined;
    preorder?: (boolean | null) | undefined;
    first_party_seller?: (boolean | null) | undefined;
    buyapi_hint?: (boolean | null) | undefined;
}
