// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * One package (tracking number) on the public tracking page.
 *
 * Intentionally minimal: carrier + tracking number (the page links to the
 * carrier's own tracking site), status, ETA, and the scan history. The
 * 17track URL and Zinc alias are deliberately NOT exposed here.
 */
export interface PublicTrackingShipment {
    carrier: string;
    tracking_number: string;
    status?: (Zinc.TrackingStatus | null) | undefined;
    estimated_delivery_date?: (string | null) | undefined;
    checkpoints?: Zinc.TrackingCheckpointResponse[] | undefined;
}
