// This file was auto-generated by Fern from our API Definition.

/**
 * Where an order is headed, for the public tracking page.
 *
 * Deliberately omits the recipient's name and phone number — everything else
 * on the shipping address (street, city, state, ZIP, country) is shown.
 */
export interface PublicTrackingDestination {
    address_line1?: (string | null) | undefined;
    address_line2?: (string | null) | undefined;
    city?: (string | null) | undefined;
    state?: (string | null) | undefined;
    postal_code?: (string | null) | undefined;
    country?: (string | null) | undefined;
}
