// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Public, unauthenticated tracking view for an order.
 *
 * Keyed by the order's random UUID (used as an unguessable share token). Shows
 * the status, destination, per-package carrier checkpoints, and the ordered
 * items — everything except the recipient's name and phone.
 */
export interface PublicTrackingResponse {
    order_id: string;
    current_status: Zinc.OrderStatus;
    /** Best-known order-level delivery estimate (destination-local calendar date); per-package estimates are on each shipment. */
    estimated_delivery_date?: (string | null) | undefined;
    destination: Zinc.PublicTrackingDestination;
    shipments: Zinc.PublicTrackingShipment[];
    items: Zinc.PublicTrackingItem[];
}
