// This file was auto-generated by Fern from our API Definition.

/**
 * A supported retailer in the public catalog — one flat object per brand.
 *
 * This is the customer-facing "what do you support?" shape: a retailer
 * identifier, where to buy from, the countries we ship to, the free-shipping
 * policy, and how orders are fulfilled (Zinc-managed vs. bring-your-own
 * account). Internal guest-checkout/credential details remain omitted.
 */
export interface PublicRetailer {
    /** Stable retailer identifier / slug, e.g. 'amazon'. */
    retailer: string;
    /** Human-friendly name, e.g. 'Amazon'. */
    display_name?: (string | null) | undefined;
    /** Retailer domain, e.g. 'amazon.com'. */
    base_url?: (string | null) | undefined;
    /** Whether Zinc can place the order for you without your own account (guest checkout or Zinc-managed credentials). */
    no_account_needed?: boolean | undefined;
    /** Whether you can order through your own retailer account. */
    use_your_account?: boolean | undefined;
    /** ISO 3166-1 alpha-2 countries we ship to (defaults to ['US']). */
    supported_countries?: string[] | undefined;
    /** Whether free shipping is offered (unconditionally or above free_shipping_threshold_cents). */
    free_shipping?: boolean | undefined;
    /** Order subtotal (cents) at/above which shipping is free; null means no threshold. */
    free_shipping_threshold_cents?: (number | null) | undefined;
}
