// This file was auto-generated by Fern from our API Definition.

/**
 * A single metered data-API call, for the "recent activity" table.
 */
export interface RecentCall {
    endpoint: string;
    at: string;
    query?: (string | null) | undefined;
    result_count?: (number | null) | undefined;
    retailer?: (string | null) | undefined;
    product_id?: (string | null) | undefined;
}
