// This file was auto-generated by Fern from our API Definition.

/**
 * What Zinc has actually done at this store.
 *
 * Deliberately coarse — a boolean and a date. Success *rates* are a
 * competitive signal.
 */
export interface RetailerCheckEvidence {
    orders_placed: boolean;
    last_order_at?: (string | null) | undefined;
}
