// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Response model for list of retailer credentials.
 */
export interface RetailerCredentialsListResponse {
    credentials: Zinc.RetailerCredentialsResponse[];
    total: number;
}
