// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Can Zinc buy from this store, and ship it where the caller wants?
 */
export interface RetailerCheckResponse {
    url: string;
    /** Canonical registrable domain, or null if the URL has none. */
    domain?: (string | null) | undefined;
    /** Zinc will attempt an order here, given whatever the store requires. True for every support tier except `unsupported` — including `untested`, a store Zinc has never seen. It is a fact about the store, not about one request: where `checkout.guest_checkout` is false the store still needs a linked account, so pass `retailer_credentials_id` to POST /orders or it will refuse. Check both fields to predict a credential-less order. */
    orderable: boolean;
    /** verified: curated, daily test order passing. active: real orders succeeded in the last 90 days. observed: Zinc has attempted orders here. untested: never seen, and Zinc will still try. unsupported: Zinc refuses; see `unsupported_reason`. */
    support: string;
    /** Null when Zinc has no catalog row for the domain. */
    retailer?: (Zinc.RetailerCheckRetailer | null) | undefined;
    /** Detected storefront platform, e.g. 'shopify'. */
    platform?: (string | null) | undefined;
    checkout?: (Zinc.RetailerCheckCheckout | null) | undefined;
    /** Declared destination countries. Null means no claim either way — the order path enforces nothing, so do not read it as 'US only'. */
    ships_to?: (string[] | null) | undefined;
    evidence?: (Zinc.RetailerCheckEvidence | null) | undefined;
    /** What `support` means for this store, in prose, and whether to go ahead. Every orderable tier says so explicitly — `untested` in particular means 'never seen it, try anyway', which the tier name alone does not convey. */
    support_detail: string;
    /** Error code Zinc would refuse with, matching POST /orders. */
    unsupported_reason?: (string | null) | undefined;
    /** What to do next. Carries the ordering instruction when `orderable` is true, and tells you not to submit when it is false. */
    how_to_order: string;
}
