// This file was auto-generated by Fern from our API Definition.

/** Universal return reason codes (Shopify + Amazon prepaid alignment). */
export const ReturnRequestReason = {
    Damaged: "damaged",
    NotDelivered: "not_delivered",
    EmptyBox: "empty_box",
    WrongItem: "wrong_item",
    Defective: "defective",
    NotAsDescribed: "not_as_described",
    WrongSize: "wrong_size",
    NoLongerNeeded: "no_longer_needed",
    ForcedCancellation: "forced_cancellation",
    Other: "other",
} as const;
export type ReturnRequestReason = (typeof ReturnRequestReason)[keyof typeof ReturnRequestReason];
