// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

export interface ReturnRequestSummary {
    id: string;
    status: Zinc.ReturnRequestStatus;
    reason: Zinc.ReturnRequestReason;
    notes?: (string | null) | undefined;
    resolution_notes?: (string | null) | undefined;
    items?: Zinc.ReturnRequestItem[] | undefined;
    label_urls?: string[] | undefined;
    created_at: string;
    updated_at: string;
}
