// This file was auto-generated by Fern from our API Definition.

export const ReturnRequestStatus = {
    Open: "open",
    Approved: "approved",
    Denied: "denied",
    Credited: "credited",
} as const;
export type ReturnRequestStatus = (typeof ReturnRequestStatus)[keyof typeof ReturnRequestStatus];
