// This file was auto-generated by Fern from our API Definition.

/**
 * A single product line on a return — which order item, how many.
 */
export interface ReturnRequestItem {
    order_item_id: string;
    quantity: number;
}
