// This file was auto-generated by Fern from our API Definition.

/**
 * Whether this sandbox has been claimed yet.
 *
 * Lets an agent learn the outcome of a claim it can't see — the thing a
 * device-code grant would give it for free (see issue #825).
 */
export interface SandboxStatusResponse {
    /** True once a human has folded this sandbox into an account — at which point this key is a real account's key and keeps working. */
    claimed: boolean;
    /** The claiming account's email, once claimed. */
    claimed_by_email?: (string | null) | undefined;
    /** What to do next given this status. */
    hint: string;
}
