// This file was auto-generated by Fern from our API Definition.

/**
 * Optional context for a sandbox key mint.
 *
 * An empty body (or none at all) is valid — nothing here gates the mint.
 */
export interface SandboxKeyCreate {
    /** (optional) Your operator's email address — we'll send them a link to claim this sandbox and its order history when they want a live account. Never used for anything else, and never required. */
    email?: (string | null) | undefined;
    /** (optional) What this key is for, e.g. 'acme-shopping-agent dev testing'. Becomes the key's label. */
    name?: (string | null) | undefined;
}
