// This file was auto-generated by Fern from our API Definition.

/**
 * A freshly minted sandbox key, with the next steps inline.
 *
 * The response doubles as documentation: agents read the bytes they get
 * back, not a docs site, so every field they need to proceed is here.
 */
export interface SandboxKeyResponse {
    /** Sandbox API key (zn_test_...). Send as `Authorization: Bearer <api_key>` — test keys route to the sandbox automatically, no extra headers needed. */
    api_key: string;
    /** Same value as `api_key`; every key response carries both names. */
    key: string;
    expires_policy: string;
    quickstart_url: string;
    /** A complete valid body for POST /orders — try it as-is. */
    example_order: Record<string, unknown>;
    /** Give this to the human you work for. Signing in there folds this sandbox — its order history and this key, which keeps working — into their Zinc account. Poll GET /sandbox/status to find out when they have. */
    claim_url: string;
    /** What to do now, in order. */
    next: string[];
}
