// This file was auto-generated by Fern from our API Definition.

/**
 * What a completed claim moved onto the account.
 */
export interface SandboxClaimResponse {
    claimed: boolean;
    orders_moved: number;
    keys_moved: number;
    message: string;
}
