// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Response from the cross-retailer search endpoint.
 */
export interface SearchResponse {
    status: string;
    query: string;
    results?: Zinc.Sku[] | undefined;
}
