// This file was auto-generated by Fern from our API Definition.

/**
 * Result order for /search. Explicit sorts order only the most relevant
 * on-topic results, so a cheap accessory that names the product can't lead a
 * price-sorted page.
 */
export const SearchSort = {
    Relevance: "relevance",
    PriceAsc: "price_asc",
    PriceDesc: "price_desc",
    Rating: "rating",
} as const;
export type SearchSort = (typeof SearchSort)[keyof typeof SearchSort];
