// This file was auto-generated by Fern from our API Definition.

export const SearchRetailer = {
    Amazon: "amazon",
    Bestbuy: "bestbuy",
    Bhphotovideo: "bhphotovideo",
    Chewy: "chewy",
    Costco: "costco",
    Homedepot: "homedepot",
    Kohls: "kohls",
    Lowes: "lowes",
    Macys: "macys",
    Newegg: "newegg",
    Staples: "staples",
    Target: "target",
    Walmart: "walmart",
    Wayfair: "wayfair",
} as const;
export type SearchRetailer = (typeof SearchRetailer)[keyof typeof SearchRetailer];
