// This file was auto-generated by Fern from our API Definition.

/**
 * A cross-retailer buyable listing. Pass `url` to /orders to buy it.
 */
export interface Sku {
    url: string;
    retailer: string;
    title?: (string | null) | undefined;
    image?: (string | null) | undefined;
    brand?: (string | null) | undefined;
    price?: (number | null) | undefined;
    stars?: (number | null) | undefined;
    num_reviews?: (number | null) | undefined;
    available?: (boolean | null) | undefined;
    /** True when the retailer listing advertises free shipping; null when unknown (never false — providers only flag the free case). */
    free_shipping?: (boolean | null) | undefined;
}
