// This file was auto-generated by Fern from our API Definition.

/**
 * One thing the starter credit is known to cover, with an orderable URL.
 */
export interface StarterPick {
    title: string;
    url: string;
    retailer: string;
    /** Retailer list price when the pick was last verified; null when not yet checked. */
    price_cents?: (number | null) | undefined;
}
