// This file was auto-generated by Fern from our API Definition.

/** Carrier-derived shipment state for a TrackingNumber. */
export const TrackingStatus = {
    Pending: "pending",
    InTransit: "in_transit",
    Delivered: "delivered",
    Undeliverable: "undeliverable",
} as const;
export type TrackingStatus = (typeof TrackingStatus)[keyof typeof TrackingStatus];
