// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Response model for tracking number data.
 *
 * ``status`` is the authoritative carrier-derived shipment state and is always
 * present. ``checkpoints`` is the per-scan timeline; it's embedded on the
 * single-order read (``GET /orders/{id}``) and, on the list endpoint, only
 * when ``include=tracking_events`` is requested.
 */
export interface TrackingNumberResponse {
    id: string;
    carrier: string;
    tracking_number: string;
    /** Zinc-issued tracking number under pseudo-carrier ZNLOGIC (format ZPY…YQ). Carrier-independent alias for this shipment; assigned once and never changes, even if the carrier tracking is corrected. */
    zinc_tracking_number?: (string | null) | undefined;
    /** Public tracking URL for the Zinc tracking number (17track.net). */
    zinc_tracking_url?: (string | null) | undefined;
    /** Carrier-derived shipment state (pending, in_transit, delivered). */
    status?: (Zinc.TrackingStatus | null) | undefined;
    /** Carrier-reported delivery estimate for this shipment, as a destination-local calendar date. Refreshed on every carrier poll; null when the carrier hasn't reported one. */
    estimated_delivery_date?: (string | null) | undefined;
    /** Carrier scan events, most recent first. Empty unless the checkpoint timeline was requested. */
    checkpoints?: Zinc.TrackingCheckpointResponse[] | undefined;
    /** Ids of the `items[]` this package carries, best effort. Null when unknown (never an empty list). Populated when the order has one item, or once a single-package order is delivered; see `item_mapping` for how much to trust it. */
    order_item_ids?: (string[] | null) | undefined;
    /** Confidence of `order_item_ids`: `exact` means the package cannot carry anything else; `inferred` means at least one entry is a best-effort guess. Null when `order_item_ids` is null. */
    item_mapping?: (TrackingNumberResponse.ItemMapping | null) | undefined;
    created_at: string;
}

export namespace TrackingNumberResponse {
    export const ItemMapping = {
        Exact: "exact",
        Inferred: "inferred",
    } as const;
    export type ItemMapping = (typeof ItemMapping)[keyof typeof ItemMapping];
}
