// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * Response model for tracking number data.
 *
 * ``status`` is the authoritative carrier-derived shipment state and is always
 * present. ``checkpoints`` is the per-scan timeline; it's embedded on the
 * single-order read (``GET /orders/{id}``) and, on the list endpoint, only
 * when ``include=tracking_events`` is requested.
 */
export interface TrackingNumberResponse {
    id: string;
    carrier: string;
    tracking_number: string;
    /** Zinc-issued tracking number under pseudo-carrier ZNLOGIC (format ZPY…YQ). Carrier-independent alias for this shipment; assigned once and never changes, even if the carrier tracking is corrected. */
    zinc_tracking_number?: (string | null) | undefined;
    /** Public tracking URL for the Zinc tracking number (17track.net). */
    zinc_tracking_url?: (string | null) | undefined;
    /** Carrier-derived shipment state (pending, in_transit, delivered). */
    status?: (Zinc.TrackingStatus | null) | undefined;
    /** Carrier-reported delivery estimate for this shipment, as a destination-local calendar date. Refreshed on every carrier poll; null when the carrier hasn't reported one. */
    estimated_delivery_date?: (string | null) | undefined;
    /** Carrier scan events, most recent first. Empty unless the checkpoint timeline was requested. */
    checkpoints?: Zinc.TrackingCheckpointResponse[] | undefined;
    created_at: string;
}
