// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../index.js";

/**
 * A single carrier-reported scan event for a tracking number.
 */
export interface TrackingCheckpointResponse {
    /** When the carrier recorded this scan event. */
    checkpoint_time: string;
    /** Carrier-derived shipment state at this checkpoint. */
    status: Zinc.TrackingStatus;
    /** Carrier-provided description of the scan. */
    message: string;
    city?: (string | null) | undefined;
    state?: (string | null) | undefined;
    country?: (string | null) | undefined;
    zip?: (string | null) | undefined;
    /** Free-form location string when city/state are absent. */
    location?: (string | null) | undefined;
}
