// This file was auto-generated by Fern from our API Definition.

export const WalletType = {
    ApiConsumption: "api_consumption",
    Purchases: "purchases",
} as const;
export type WalletType = (typeof WalletType)[keyof typeof WalletType];
