// This file was auto-generated by Fern from our API Definition.

/**
 * The caller's webhook endpoint: where events go and the HMAC secret that
 * signs them. Both are null until registered.
 */
export interface WebhookEndpointResponse {
    webhook_url: string | null;
    webhook_secret: string | null;
}
