// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {}
 *     }
 */
export interface CreateDeviceCodeDeviceCodePostRequest {
    authorization?: string | null;
    body: Zinc.DeviceCodeCreate | null;
}
