// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_code: "user_code"
 *     }
 */
export interface DescribeDeviceCodeDeviceCodesUserCodeGetRequest {
    user_code: string;
}
