// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_code: "user_code",
 *         granted: true
 *     }
 */
export interface DeviceApproveRequest {
    authorization?: string | null;
    user_code: string;
    granted: boolean;
}
