// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         device_code: "device_code"
 *     }
 */
export interface DeviceTokenRequest {
    device_code: string;
}
