// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as Zinc from "../../../index.js";

export declare namespace HealthClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class HealthClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<HealthClient.Options>;

    constructor(options: HealthClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Customer-facing platform health.
     *
     * No auth. Cached in-process for 4 minutes — at the marketing site's 5-min
     * cron cadence, the DB is touched at most ~once per tick.
     *
     * @param {HealthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.health.getPublicHealth()
     */
    public getPublicHealth(
        requestOptions?: HealthClient.RequestOptions,
    ): core.HttpResponsePromise<Zinc.PublicHealthResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPublicHealth(requestOptions));
    }

    private async __getPublicHealth(
        requestOptions?: HealthClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zinc.PublicHealthResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                "health",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Zinc.PublicHealthResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ZincError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/health");
    }
}
