// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             products: [{
 *                     url: "https://www.amazon.com/dp/B07JGBW826"
 *                 }],
 *             shipping_address: {
 *                 first_name: "first_name",
 *                 last_name: "last_name",
 *                 address_line1: "address_line1",
 *                 city: "city",
 *                 postal_code: "postal_code",
 *                 phone_number: "phone_number"
 *             },
 *             max_price: 1
 *         }
 *     }
 */
export interface CreateOrderOrdersPostRequest {
    authorization?: string | null;
    body: Zinc.OrderCreate;
}
