// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batch_id: "batch_id"
 *     }
 */
export interface DownloadBulkResultsOrdersBulkBatchIdResultsCsvGetRequest {
    batch_id: string;
    authorization?: string | null;
}
