// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ExportOrdersCsvOrdersExportGetRequest {
    /** Filter by order ID (partial match) */
    order_id?: string | null;
    /** Partial match on order ID OR tracking number */
    search?: string | null;
    /** Filter by order status */
    status_filter?: string | null;
    /** Filter by the retailer's own order number (exact match) */
    merchant_order_id?: string | null;
    /** Filter to orders having at least one tracking number with this status */
    tracking_status?: string | null;
    /** Only orders with (true) or without (false) tracking */
    has_tracking?: boolean | null;
    /** `open` or `closed` return requests; omit for no filter */
    return_status?: string | null;
    /** Only orders created at/after this instant (inclusive) */
    created_after?: string | null;
    /** Only orders created before this instant (exclusive) */
    created_before?: string | null;
    /** Top-level `metadata` key to match; send with `metadata_value` */
    metadata_key?: string | null;
    /** Exact value `metadata_key` must equal; send with `metadata_key` */
    metadata_value?: string | null;
    /** Filter to orders placed by one org teammate, matched as a case-insensitive substring of their email. Only ever narrows within the caller's organization; a solo user can only match their own address. */
    user_email?: string | null;
    authorization?: string | null;
}
