// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         order_id: "order_id"
 *     }
 */
export interface GetOrderTimelineOrdersOrderIdTimelineGetRequest {
    order_id: string;
    authorization?: string | null;
}
