// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListBulkUploadsOrdersBulkGetRequest {
    limit?: number;
    offset?: number;
    authorization?: string | null;
}
