// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListOrdersOrdersGetRequest {
    /** Number of orders to return */
    limit?: number;
    /** Number of orders to skip */
    offset?: number;
    /** Filter by order ID (partial match) */
    order_id?: string | null;
    /** Partial match on order ID OR tracking number */
    search?: string | null;
    /** Filter by order status */
    status_filter?: string | null;
    /** Filter to orders having at least one tracking number with this status */
    tracking_status?: string | null;
    /** If true, only orders with at least one tracking number; if false, only orders with none */
    has_tracking?: boolean | null;
    /** Filter by return-request status. `open` → orders with at least one open return. `closed` → orders with at least one approved or denied return. Omit for no filter. */
    return_status?: string | null;
    /** Only orders created at/after this instant (inclusive) */
    created_after?: string | null;
    /** Only orders created before this instant (exclusive) */
    created_before?: string | null;
    /** Optional expansions. `tracking_events` embeds the full carrier checkpoint timeline (and latest status) on each tracking number; omitted by default to keep list payloads small. */
    include?: string | string[];
    authorization?: string | null;
}
