// This file was auto-generated by Fern from our API Definition.

/** Retailer identifier */
export const GetProductDetailsProductsProductIdGetRequestRetailer = {
    Amazon: "amazon",
    Walmart: "walmart",
} as const;
export type GetProductDetailsProductsProductIdGetRequestRetailer =
    (typeof GetProductDetailsProductsProductIdGetRequestRetailer)[keyof typeof GetProductDetailsProductsProductIdGetRequestRetailer];
