// This file was auto-generated by Fern from our API Definition.

/**
 * Every seller's offer for the product, passed through from the retailer. Shopify stores and Etsy listings have a single seller, so they are rejected here and report price and availability on the details endpoint; Best Buy's per-condition prices are on the details endpoint too.
 */
export interface GetProductOffersProductsProductIdOffersGetResponse {
    /** `completed` when the payload below is populated. `processing` when `async=true` was passed and the fetch is still running — poll again. `failed` when the retailer returned an error; see `code` and `message`. */
    status: GetProductOffersProductsProductIdOffersGetResponse.Status;
    /** Only on `status: failed`. Machine-readable error code, e.g. `product_not_found`, `invalid_request`. */
    code?: string | undefined;
    /** Only on `status: failed`. Human-readable explanation. */
    message?: string | undefined;
    /** Retailer that served the offers, e.g. `amazon`. */
    retailer?: string | undefined;
    /** Amazon only. The product's ASIN. */
    asin?: string | undefined;
    /** One entry per seller offer. Empty when the product has no buyable offers. */
    offers?: GetProductOffersProductsProductIdOffersGetResponse.Offers.Item[] | undefined;
    /** Unix time the offers were retrieved. */
    timestamp?: number | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace GetProductOffersProductsProductIdOffersGetResponse {
    /** `completed` when the payload below is populated. `processing` when `async=true` was passed and the fetch is still running — poll again. `failed` when the retailer returned an error; see `code` and `message`. */
    export const Status = {
        Completed: "completed",
        Processing: "processing",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type Offers = Offers.Item[];

    export namespace Offers {
        export interface Item {
            /** Retailer's identifier for this offer. Amazon: the offer listing id. */
            offer_id?: (string | null) | undefined;
            /** Item price in cents, excluding shipping. */
            price?: number | undefined;
            /** Item condition. */
            condition?: Item.Condition | undefined;
            /** Whether the offer can currently be bought. */
            available?: boolean | undefined;
            /** Who is selling this offer. */
            seller?: Item.Seller | undefined;
            /** Shipped by the retailer rather than the seller. Amazon: the offer ships with Prime. */
            marketplace_fulfilled?: boolean | undefined;
            /** Amazon only. Only Prime members can buy this offer. */
            prime_only?: boolean | undefined;
            /** Ships from outside the United States. */
            international?: boolean | undefined;
            /** Amazon only. Add-on item that can only be bought alongside other items. */
            addon?: boolean | undefined;
            /** Minimum order quantity, when the seller imposes one. */
            minimum_quantity?: (number | null) | undefined;
            /** Time before the seller ships. */
            handling_days?: Item.HandlingDays | undefined;
            /** Shipping methods offered by this seller. */
            shipping_options?: Item.ShippingOptions.Item[] | undefined;
        }

        export namespace Item {
            /** Item condition. */
            export const Condition = {
                New: "New",
                Refurbished: "Refurbished",
                UsedLikeNew: "Used - Like New",
                UsedVeryGood: "Used - Very Good",
                UsedGood: "Used - Good",
                UsedAcceptable: "Used - Acceptable",
                Unacceptable: "Unacceptable",
            } as const;
            export type Condition = (typeof Condition)[keyof typeof Condition];

            /**
             * Who is selling this offer.
             */
            export interface Seller {
                /** Retailer's seller id. */
                id?: (string | null) | undefined;
                /** Seller display name. */
                name?: (string | null) | undefined;
                /** Seller's lifetime rating count. */
                num_ratings?: (number | null) | undefined;
                /** Share of positive seller ratings, 0–100. */
                percent_positive?: (number | null) | undefined;
                /** Sold by the retailer itself (e.g. Amazon.com). */
                first_party?: boolean | undefined;
            }

            /**
             * Time before the seller ships.
             */
            export interface HandlingDays {
                /** Minimum handling time in days. */
                min?: number | undefined;
                /** Maximum handling time in days. */
                max?: number | undefined;
            }

            export type ShippingOptions = ShippingOptions.Item[];

            export namespace ShippingOptions {
                export interface Item {
                    /** Shipping speed, e.g. `standard`, `one-day`. */
                    name?: string | undefined;
                    /** Shipping price in cents. */
                    price?: number | undefined;
                    delivery_days?: Item.DeliveryDays | undefined;
                }

                export namespace Item {
                    export interface DeliveryDays {
                        /** Earliest delivery, in days. */
                        min?: number | undefined;
                        /** Latest delivery, in days. */
                        max?: number | undefined;
                    }
                }
            }
        }
    }
}
