// This file was auto-generated by Fern from our API Definition.

/** Retailer identifier */
export const GetProductOffersProductsProductIdOffersGetRequestRetailer = {
    Amazon: "amazon",
    Walmart: "walmart",
} as const;
export type GetProductOffersProductsProductIdOffersGetRequestRetailer =
    (typeof GetProductOffersProductsProductIdOffersGetRequestRetailer)[keyof typeof GetProductOffersProductsProductIdOffersGetRequestRetailer];
