// This file was auto-generated by Fern from our API Definition.

/** Retailer identifier */
export const SearchProductsProductsSearchGetRequestRetailer = {
    Amazon: "amazon",
    Walmart: "walmart",
} as const;
export type SearchProductsProductsSearchGetRequestRetailer =
    (typeof SearchProductsProductsSearchGetRequestRetailer)[keyof typeof SearchProductsProductsSearchGetRequestRetailer];
