// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface CheckRetailerRetailersCheckGetRequest {
    /** A product or store URL, e.g. https://shop.aloyoga.com/products/x */
    url: string;
    /** Destination country as an ISO 3166-1 alpha-2 code (e.g. 'US', 'GB'). Case-insensitive. Longer spellings such as 'USA' are rejected — the error names the code to use. Omit to skip the shipping check. Runs the same gate `POST /orders` applies, so the two cannot disagree. */
    country?: string | null;
}
