// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListRetailersRetailersGetRequest {
    /** Number of retailers to return */
    limit?: number;
    /** Number of retailers to skip */
    offset?: number;
    /** Filter by name (case-insensitive partial match) */
    name?: string | null;
    /** Pass `all` to include the long tail Zinc has ordered from but not curated (hundreds of brands). Omit for the curated set. This selects how much of the catalog to return; it is not a filter on an entry's `support` tier. */
    include?: string | null;
}
