// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListRetailersRetailersGetRequest {
    /** Number of retailers to return */
    limit?: number;
    /** Number of retailers to skip */
    offset?: number;
    /** Filter by name (case-insensitive partial match) */
    name?: string | null;
}
