// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         q: "q"
 *     }
 */
export interface SearchSearchGetRequest {
    /** Search term */
    q: string;
    authorization?: string | null;
}
