// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         return_request_id: "return_request_id"
 *     }
 */
export interface GetReturnRequestReturnsReturnRequestIdGetRequest {
    return_request_id: string;
    authorization?: string | null;
}
