// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListReturnRequestsReturnsGetRequest {
    /** Page size (default 50, max 500). Responses include `total` for paging past it. */
    limit?: number;
    /** Number of returns to skip */
    offset?: number;
    /** Partial match on order ID */
    search?: string | null;
    /** Filter by return status */
    status?: string | null;
    authorization?: string | null;
}
