// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../../../../index.js";

/**
 * @example
 *     {
 *         order_id: "order_id",
 *         items: [{
 *                 order_item_id: "order_item_id",
 *                 quantity: 1
 *             }],
 *         reason: "damaged"
 *     }
 */
export interface ReturnRequestCreate {
    authorization?: string | null;
    order_id: string;
    /** Per-product lines being returned */
    items: Zinc.ReturnRequestItem[];
    reason: Zinc.ReturnRequestReason;
    notes?: string | null;
}
