// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentClient", () => {
    test("createMppOrder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            products: [{ url: "https://www.amazon.com/dp/B07JGBW826" }],
            shipping_address: {
                first_name: "first_name",
                last_name: "last_name",
                address_line1: "address_line1",
                city: "city",
                postal_code: "postal_code",
                phone_number: "phone_number",
            },
            max_price: 1,
        };
        const rawResponseBody = {
            id: "id",
            status: "pending",
            max_price: 1,
            attempts: 1,
            items: [
                {
                    id: "id",
                    url: "url",
                    quantity: 1,
                    variant: [{ label: "label", value: "value" }],
                    condition_in: ["New"],
                    condition_not_in: ["New"],
                    status: "pending",
                    cancellation_reason: "cancellation_reason",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            shipping_address: { key: "value" },
            metadata: { key: "value" },
            po_number: "po_number",
            handling_days_max: 1,
            is_gift: true,
            retailer_credentials_id: "retailer_credentials_id",
            retailer_credentials_uuid: "retailer_credentials_uuid",
            job_result: {
                success: true,
                error: "error",
                error_type: "error_type",
                error_details: {
                    code: "code",
                    message: "message",
                    address_validation_reasons: ["address_validation_reasons"],
                    field_errors: [{ field: "field", code: "code" }],
                },
                price_components: {
                    subtotal: 1,
                    tax: 1,
                    shipping: 1,
                    discount: 1,
                    fees: 1,
                    total: 1,
                    converted_payment_total: 1,
                    currency: "currency",
                    payment_currency: "payment_currency",
                    line_items: [{ key: "value" }],
                },
                estimated_delivery: "estimated_delivery",
                merchant_order_ids: [{ key: "value" }],
            },
            tracking_numbers: [
                {
                    id: "id",
                    carrier: "carrier",
                    tracking_number: "tracking_number",
                    zinc_tracking_number: "zinc_tracking_number",
                    zinc_tracking_url: "zinc_tracking_url",
                    status: "pending",
                    estimated_delivery_date: "2023-01-15",
                    checkpoints: [{ checkpoint_time: "2024-01-15T09:30:00Z", status: "pending", message: "message" }],
                    created_at: "2024-01-15T09:30:00Z",
                },
            ],
            created_by: "created_by",
            user_id: 1,
            returns: [
                {
                    id: "id",
                    status: "open",
                    reason: "damaged",
                    notes: "notes",
                    resolution_notes: "resolution_notes",
                    items: [{ order_item_id: "order_item_id", quantity: 1 }],
                    label_urls: ["label_urls"],
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            connect: {
                state: "state",
                secured_amount: 1,
                order_cost: 1,
                customer_margin: 1,
                zinc_fee: 1,
                stripe_fee: 1,
                final_charge: 1,
                transfer_amount: 1,
                payment_intent_id: "payment_intent_id",
                connected_account_id: "connected_account_id",
                simulated: true,
            },
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/agent/orders")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.createMppOrder({
            body: {
                products: [
                    {
                        url: "https://www.amazon.com/dp/B07JGBW826",
                    },
                ],
                shipping_address: {
                    first_name: "first_name",
                    last_name: "last_name",
                    address_line1: "address_line1",
                    city: "city",
                    postal_code: "postal_code",
                    phone_number: "phone_number",
                },
                max_price: 1,
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createMppOrder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            products: [{ url: "url" }, { url: "url" }],
            shipping_address: {
                first_name: "first_name",
                last_name: "last_name",
                address_line1: "address_line1",
                city: "city",
                postal_code: "postal_code",
                phone_number: "phone_number",
            },
            max_price: 1,
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/orders")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.createMppOrder({
                body: {
                    products: [
                        {
                            url: "url",
                        },
                        {
                            url: "url",
                        },
                    ],
                    shipping_address: {
                        first_name: "first_name",
                        last_name: "last_name",
                        address_line1: "address_line1",
                        city: "city",
                        postal_code: "postal_code",
                        phone_number: "phone_number",
                    },
                    max_price: 1,
                },
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("createMppOrder (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            products: [{ url: "url" }, { url: "url" }],
            shipping_address: {
                first_name: "first_name",
                last_name: "last_name",
                address_line1: "address_line1",
                city: "city",
                postal_code: "postal_code",
                phone_number: "phone_number",
            },
            max_price: 1,
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/orders")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.createMppOrder({
                body: {
                    products: [
                        {
                            url: "url",
                        },
                        {
                            url: "url",
                        },
                    ],
                    shipping_address: {
                        first_name: "first_name",
                        last_name: "last_name",
                        address_line1: "address_line1",
                        city: "city",
                        postal_code: "postal_code",
                        phone_number: "phone_number",
                    },
                    max_price: 1,
                },
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("search (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "status",
            query: "query",
            results: [
                {
                    url: "url",
                    retailer: "retailer",
                    title: "title",
                    image: "image",
                    brand: "brand",
                    price: 1,
                    stars: 1.1,
                    num_reviews: 1,
                    available: true,
                },
            ],
        };

        server.mockEndpoint().get("/agent/search").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agent.search({
            q: "q",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("search (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agent/search").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.search({
                q: "q",
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("search (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agent/search").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.search({
                q: "q",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("searchPost (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "status",
            query: "query",
            results: [
                {
                    url: "url",
                    retailer: "retailer",
                    title: "title",
                    image: "image",
                    brand: "brand",
                    price: 1,
                    stars: 1.1,
                    num_reviews: 1,
                    available: true,
                },
            ],
        };

        server.mockEndpoint().post("/agent/search").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agent.searchPost({
            q: "q",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("searchPost (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/agent/search").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.searchPost({
                q: "q",
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("searchPost (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/agent/search").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.searchPost({
                q: "q",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("productSearch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "status",
            results: [
                {
                    product_id: "product_id",
                    title: "title",
                    image: "image",
                    brand: "brand",
                    price: 1,
                    stars: 1.1,
                    num_reviews: 1,
                    num_offers_estimate: 1,
                    num_sales: 1,
                    fresh: true,
                    prime: true,
                    pantry: true,
                    addon: true,
                    ship_price: 1,
                    upc: "upc",
                    mpn: "mpn",
                    available: true,
                    available_online: true,
                    available_instore: true,
                    freight_shipping: true,
                    preorder: true,
                    first_party_seller: true,
                    buyapi_hint: true,
                },
            ],
            next_page: 1,
        };

        server
            .mockEndpoint()
            .get("/agent/products/search")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.productSearch({
            query: "query",
            retailer: "amazon",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("productSearch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agent/products/search")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productSearch({
                query: "query",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("productSearch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agent/products/search")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productSearch({
                query: "query",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("productSearchPost (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "status",
            results: [
                {
                    product_id: "product_id",
                    title: "title",
                    image: "image",
                    brand: "brand",
                    price: 1,
                    stars: 1.1,
                    num_reviews: 1,
                    num_offers_estimate: 1,
                    num_sales: 1,
                    fresh: true,
                    prime: true,
                    pantry: true,
                    addon: true,
                    ship_price: 1,
                    upc: "upc",
                    mpn: "mpn",
                    available: true,
                    available_online: true,
                    available_instore: true,
                    freight_shipping: true,
                    preorder: true,
                    first_party_seller: true,
                    buyapi_hint: true,
                },
            ],
            next_page: 1,
        };

        server
            .mockEndpoint()
            .post("/agent/products/search")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.productSearchPost({
            query: "query",
            retailer: "amazon",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("productSearchPost (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/products/search")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productSearchPost({
                query: "query",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("productSearchPost (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/products/search")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productSearchPost({
                query: "query",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("productOffers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agent/products/offers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.productOffers({
            product_id: "product_id",
            retailer: "amazon",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("productOffers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agent/products/offers")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productOffers({
                product_id: "product_id",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("productOffers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agent/products/offers")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productOffers({
                product_id: "product_id",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("productOffersPost (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/products/offers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.productOffersPost({
            product_id: "product_id",
            retailer: "amazon",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("productOffersPost (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/products/offers")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productOffersPost({
                product_id: "product_id",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("productOffersPost (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/products/offers")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productOffersPost({
                product_id: "product_id",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("productDetails (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agent/products/details")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.productDetails({
            product_id: "product_id",
            retailer: "amazon",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("productDetails (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agent/products/details")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productDetails({
                product_id: "product_id",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("productDetails (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agent/products/details")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productDetails({
                product_id: "product_id",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("productDetailsPost (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/products/details")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.productDetailsPost({
            product_id: "product_id",
            retailer: "amazon",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("productDetailsPost (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/products/details")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productDetailsPost({
                product_id: "product_id",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("productDetailsPost (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/products/details")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.productDetailsPost({
                product_id: "product_id",
                retailer: "amazon",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
