// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DeviceClient", () => {
    test("createDeviceCode (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            device_code: "device_code",
            user_code: "user_code",
            verification_uri: "verification_uri",
            verification_uri_complete: "verification_uri_complete",
            expires_in: 1,
            interval: 1,
            human_message: "human_message",
            next: "next",
        };

        server
            .mockEndpoint()
            .post("/device/code")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.device.createDeviceCode({
            body: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createDeviceCode (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = null;
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/device/code")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.device.createDeviceCode({
                body: null,
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("describeDeviceCode (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            user_code: "user_code",
            name: "name",
            source: "source",
            sandbox_attached: true,
            starter_credit_cents: 1,
            status: "status",
        };

        server
            .mockEndpoint()
            .get("/device/codes/user_code")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.device.describeDeviceCode({
            user_code: "user_code",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("describeDeviceCode (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/device/codes/user_code")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.device.describeDeviceCode({
                user_code: "user_code",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("decideDeviceCode (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { user_code: "user_code", granted: true };
        const rawResponseBody = { status: "status", name: "name", message: "message" };

        server
            .mockEndpoint()
            .post("/device/approve")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.device.decideDeviceCode({
            user_code: "user_code",
            granted: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("decideDeviceCode (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { user_code: "buzz", granted: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/device/approve")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.device.decideDeviceCode({
                user_code: "buzz",
                granted: true,
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("redeemDeviceCode (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { device_code: "device_code" };
        const rawResponseBody = {
            id: "id",
            key: "key",
            name: "name",
            is_active: true,
            is_test: true,
            created_at: "2024-01-15T09:30:00Z",
            wallet_balance_cents: 1,
            sandbox: { orders_moved: 1, keys_moved: 1, note: "note" },
            starter_credit: {
                cents: 1,
                reason: "reason",
                wallet_balance_cents: 1,
                max_price_cents: 1,
                message: "message",
                picks: [{ title: "title", url: "url", retailer: "retailer" }],
            },
            api_key: "api_key",
        };

        server
            .mockEndpoint()
            .post("/device/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.device.redeemDeviceCode({
            device_code: "device_code",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("redeemDeviceCode (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { device_code: "blackcurrant...." };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/device/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.device.redeemDeviceCode({
                device_code: "blackcurrant....",
            });
        }).rejects.toThrow(Zinc.BadRequestError);
    });

    test("redeemDeviceCode (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { device_code: "blackcurrant...." };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/device/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.device.redeemDeviceCode({
                device_code: "blackcurrant....",
            });
        }).rejects.toThrow(Zinc.ForbiddenError);
    });

    test("redeemDeviceCode (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { device_code: "blackcurrant...." };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/device/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.device.redeemDeviceCode({
                device_code: "blackcurrant....",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
