// This file was auto-generated by Fern from our API Definition.

import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("HealthClient", () => {
    test("getPublicHealth", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "up",
            components: { db: "up", queue: "up", ordering: "up" },
            updated_at: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/health").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.health.getPublicHealth();
        expect(response).toEqual(rawResponseBody);
    });
});
