// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ManagedAccountsClient", () => {
    test("listRetailerCredentials (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            credentials: [
                {
                    id: "id",
                    short_id: "short_id",
                    email: "email",
                    retailer: "retailer",
                    retailer_id: 1,
                    has_totp: true,
                    has_forwarding: true,
                    is_paused: true,
                    locked_by_job_id: "locked_by_job_id",
                    cooldown_minutes: 1,
                    last_used_at: "2024-01-15T09:30:00Z",
                    retailer_config: { key: "value" },
                    forwarding_email: "forwarding_email",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            total: 1,
        };

        server.mockEndpoint().get("/managed-accounts").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.managedAccounts.listRetailerCredentials();
        expect(response).toEqual(rawResponseBody);
    });

    test("listRetailerCredentials (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/managed-accounts").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.managedAccounts.listRetailerCredentials();
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("createRetailerCredentials (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = {
            id: "id",
            short_id: "short_id",
            email: "email",
            retailer: "retailer",
            retailer_id: 1,
            has_totp: true,
            has_forwarding: true,
            is_paused: true,
            locked_by_job_id: "locked_by_job_id",
            cooldown_minutes: 1,
            last_used_at: "2024-01-15T09:30:00Z",
            retailer_config: { key: "value" },
            forwarding_email: "forwarding_email",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/managed-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.managedAccounts.createRetailerCredentials({
            email: "email",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createRetailerCredentials (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/managed-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.managedAccounts.createRetailerCredentials({
                email: "email",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("updateRetailerCredentials (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            short_id: "short_id",
            email: "email",
            retailer: "retailer",
            retailer_id: 1,
            has_totp: true,
            has_forwarding: true,
            is_paused: true,
            locked_by_job_id: "locked_by_job_id",
            cooldown_minutes: 1,
            last_used_at: "2024-01-15T09:30:00Z",
            retailer_config: { key: "value" },
            forwarding_email: "forwarding_email",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .put("/managed-accounts/short_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.managedAccounts.updateRetailerCredentials({
            short_id: "short_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateRetailerCredentials (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/managed-accounts/short_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.managedAccounts.updateRetailerCredentials({
                short_id: "short_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("deleteRetailerCredentials (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/managed-accounts/short_id").respondWith().statusCode(200).build();

        const response = await client.managedAccounts.deleteRetailerCredentials({
            short_id: "short_id",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteRetailerCredentials (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/managed-accounts/short_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.managedAccounts.deleteRetailerCredentials({
                short_id: "short_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
