// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("OrdersClient", () => {
    test("validateBulkUpload (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            filename: "filename",
            total_rows: 1,
            valid_rows: 1,
            invalid_rows: 1,
            estimated_total_cents: 1,
            wallet_balance_cents: 1,
            sufficient_funds: true,
            rows: [
                {
                    index: 1,
                    ok: true,
                    errors: ["errors"],
                    product_urls: ["product_urls"],
                    quantities: [1],
                    recipient: "recipient",
                    destination: "destination",
                    max_price: 1,
                    retailer_credentials_id: "retailer_credentials_id",
                    passthrough: { key: "value" },
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/orders/bulk/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.orders.validateBulkUpload({
            body: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("validateBulkUpload (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/orders/bulk/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.orders.validateBulkUpload({
                body: {},
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("listBulkUploads (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            batches: [
                {
                    id: "id",
                    filename: "filename",
                    status: "pending",
                    row_count: 1,
                    placed_count: 1,
                    failed_count: 1,
                    notify_on_complete: true,
                    notified_at: "2024-01-15T09:30:00Z",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                    rows: [{ index: 1, status: "status" }],
                },
            ],
            total: 1,
        };

        server.mockEndpoint().get("/orders/bulk").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.orders.listBulkUploads();
        expect(response).toEqual(rawResponseBody);
    });

    test("listBulkUploads (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/orders/bulk").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.orders.listBulkUploads();
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("createBulkUpload (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            filename: "filename",
            status: "pending",
            row_count: 1,
            placed_count: 1,
            failed_count: 1,
            notify_on_complete: true,
            notified_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            rows: [
                {
                    index: 1,
                    status: "status",
                    order_id: "order_id",
                    order_status: "order_status",
                    error: "error",
                    recipient: "recipient",
                    product_urls: ["product_urls"],
                    passthrough: { key: "value" },
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/orders/bulk")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.orders.createBulkUpload({
            body: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createBulkUpload (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/orders/bulk")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.orders.createBulkUpload({
                body: {},
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("getBulkUpload (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            filename: "filename",
            status: "pending",
            row_count: 1,
            placed_count: 1,
            failed_count: 1,
            notify_on_complete: true,
            notified_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            rows: [
                {
                    index: 1,
                    status: "status",
                    order_id: "order_id",
                    order_status: "order_status",
                    error: "error",
                    recipient: "recipient",
                    product_urls: ["product_urls"],
                    passthrough: { key: "value" },
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/orders/bulk/batch_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.orders.getBulkUpload({
            batch_id: "batch_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBulkUpload (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/orders/bulk/batch_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.orders.getBulkUpload({
                batch_id: "batch_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("listOrders (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            orders: [
                {
                    id: "id",
                    status: "pending",
                    max_price: 1,
                    attempts: 1,
                    items: [
                        {
                            id: "id",
                            url: "url",
                            quantity: 1,
                            status: "pending",
                            created_at: "2024-01-15T09:30:00Z",
                            updated_at: "2024-01-15T09:30:00Z",
                        },
                    ],
                    shipping_address: { key: "value" },
                    metadata: { key: "value" },
                    po_number: "po_number",
                    handling_days_max: 1,
                    is_gift: true,
                    gift_message: "gift_message",
                    retailer_credentials_id: "retailer_credentials_id",
                    retailer_credentials_uuid: "retailer_credentials_uuid",
                    merchant_order_ids: ["merchant_order_ids"],
                    tracking_numbers: [
                        {
                            id: "id",
                            carrier: "carrier",
                            tracking_number: "tracking_number",
                            created_at: "2024-01-15T09:30:00Z",
                        },
                    ],
                    created_by: "created_by",
                    user_id: 1,
                    returns: [
                        {
                            id: "id",
                            status: "open",
                            reason: "damaged",
                            created_at: "2024-01-15T09:30:00Z",
                            updated_at: "2024-01-15T09:30:00Z",
                        },
                    ],
                    connect: { state: "state" },
                    customer_notifications: { email: "email" },
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            total: 1,
            limit: 1,
            offset: 1,
        };

        server.mockEndpoint().get("/orders").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.orders.listOrders();
        expect(response).toEqual(rawResponseBody);
    });

    test("listOrders (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/orders").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.orders.listOrders();
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("createOrder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            products: [{ url: "https://www.amazon.com/dp/B07JGBW826" }],
            shipping_address: {
                first_name: "first_name",
                last_name: "last_name",
                address_line1: "address_line1",
                city: "city",
                postal_code: "postal_code",
                phone_number: "phone_number",
            },
            max_price: 1,
        };
        const rawResponseBody = {
            id: "id",
            status: "pending",
            max_price: 1,
            attempts: 1,
            items: [
                {
                    id: "id",
                    url: "url",
                    quantity: 1,
                    variant: [{ label: "label", value: "value" }],
                    condition_in: ["New"],
                    condition_not_in: ["New"],
                    status: "pending",
                    cancellation_reason: "cancellation_reason",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            shipping_address: { key: "value" },
            metadata: { key: "value" },
            po_number: "po_number",
            handling_days_max: 1,
            is_gift: true,
            gift_message: "gift_message",
            retailer_credentials_id: "retailer_credentials_id",
            retailer_credentials_uuid: "retailer_credentials_uuid",
            job_result: {
                success: true,
                error: "error",
                error_type: "error_type",
                error_details: {
                    code: "code",
                    message: "message",
                    address_validation_reasons: ["address_validation_reasons"],
                    field_errors: [{ field: "field", code: "code" }],
                },
                price_components: {
                    subtotal: 1,
                    tax: 1,
                    shipping: 1,
                    discount: 1,
                    fees: 1,
                    total: 1,
                    converted_payment_total: 1,
                    currency: "currency",
                    payment_currency: "payment_currency",
                    cart_items: [{}],
                    line_items: [{ key: "value" }],
                },
                estimated_delivery: "estimated_delivery",
                merchant_order_ids: [{ key: "value" }],
            },
            merchant_order_ids: ["merchant_order_ids"],
            tracking_numbers: [
                {
                    id: "id",
                    carrier: "carrier",
                    tracking_number: "tracking_number",
                    zinc_tracking_number: "zinc_tracking_number",
                    zinc_tracking_url: "zinc_tracking_url",
                    status: "pending",
                    estimated_delivery_date: "2023-01-15",
                    checkpoints: [{ checkpoint_time: "2024-01-15T09:30:00Z", status: "pending", message: "message" }],
                    created_at: "2024-01-15T09:30:00Z",
                },
            ],
            created_by: "created_by",
            user_id: 1,
            returns: [
                {
                    id: "id",
                    status: "open",
                    reason: "damaged",
                    notes: "notes",
                    resolution_notes: "resolution_notes",
                    items: [{ order_item_id: "order_item_id", quantity: 1 }],
                    label_urls: ["label_urls"],
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            connect: {
                state: "state",
                secured_amount: 1,
                order_cost: 1,
                customer_margin: 1,
                zinc_fee: 1,
                stripe_fee: 1,
                final_charge: 1,
                transfer_amount: 1,
                payment_intent_id: "payment_intent_id",
                connected_account_id: "connected_account_id",
                simulated: true,
            },
            customer_notifications: { email: "email", delivered: true },
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/orders")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.orders.createOrder({
            body: {
                products: [
                    {
                        url: "https://www.amazon.com/dp/B07JGBW826",
                    },
                ],
                shipping_address: {
                    first_name: "first_name",
                    last_name: "last_name",
                    address_line1: "address_line1",
                    city: "city",
                    postal_code: "postal_code",
                    phone_number: "phone_number",
                },
                max_price: 1,
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createOrder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            products: [{ url: "url" }, { url: "url" }],
            shipping_address: {
                first_name: "first_name",
                last_name: "last_name",
                address_line1: "address_line1",
                city: "city",
                postal_code: "postal_code",
                phone_number: "phone_number",
            },
            max_price: 1,
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/orders")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.orders.createOrder({
                body: {
                    products: [
                        {
                            url: "url",
                        },
                        {
                            url: "url",
                        },
                    ],
                    shipping_address: {
                        first_name: "first_name",
                        last_name: "last_name",
                        address_line1: "address_line1",
                        city: "city",
                        postal_code: "postal_code",
                        phone_number: "phone_number",
                    },
                    max_price: 1,
                },
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("listTestProducts", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/orders/test-products")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.orders.listTestProducts();
        expect(response).toEqual(rawResponseBody);
    });

    test("getOrder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            status: "pending",
            max_price: 1,
            attempts: 1,
            items: [
                {
                    id: "id",
                    url: "url",
                    quantity: 1,
                    variant: [{ label: "label", value: "value" }],
                    condition_in: ["New"],
                    condition_not_in: ["New"],
                    status: "pending",
                    cancellation_reason: "cancellation_reason",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            shipping_address: { key: "value" },
            metadata: { key: "value" },
            po_number: "po_number",
            handling_days_max: 1,
            is_gift: true,
            gift_message: "gift_message",
            retailer_credentials_id: "retailer_credentials_id",
            retailer_credentials_uuid: "retailer_credentials_uuid",
            job_result: {
                success: true,
                error: "error",
                error_type: "error_type",
                error_details: {
                    code: "code",
                    message: "message",
                    address_validation_reasons: ["address_validation_reasons"],
                    field_errors: [{ field: "field", code: "code" }],
                },
                price_components: {
                    subtotal: 1,
                    tax: 1,
                    shipping: 1,
                    discount: 1,
                    fees: 1,
                    total: 1,
                    converted_payment_total: 1,
                    currency: "currency",
                    payment_currency: "payment_currency",
                    cart_items: [{}],
                    line_items: [{ key: "value" }],
                },
                estimated_delivery: "estimated_delivery",
                merchant_order_ids: [{ key: "value" }],
            },
            merchant_order_ids: ["merchant_order_ids"],
            tracking_numbers: [
                {
                    id: "id",
                    carrier: "carrier",
                    tracking_number: "tracking_number",
                    zinc_tracking_number: "zinc_tracking_number",
                    zinc_tracking_url: "zinc_tracking_url",
                    status: "pending",
                    estimated_delivery_date: "2023-01-15",
                    checkpoints: [{ checkpoint_time: "2024-01-15T09:30:00Z", status: "pending", message: "message" }],
                    created_at: "2024-01-15T09:30:00Z",
                },
            ],
            created_by: "created_by",
            user_id: 1,
            returns: [
                {
                    id: "id",
                    status: "open",
                    reason: "damaged",
                    notes: "notes",
                    resolution_notes: "resolution_notes",
                    items: [{ order_item_id: "order_item_id", quantity: 1 }],
                    label_urls: ["label_urls"],
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            connect: {
                state: "state",
                secured_amount: 1,
                order_cost: 1,
                customer_margin: 1,
                zinc_fee: 1,
                stripe_fee: 1,
                final_charge: 1,
                transfer_amount: 1,
                payment_intent_id: "payment_intent_id",
                connected_account_id: "connected_account_id",
                simulated: true,
            },
            customer_notifications: { email: "email", delivered: true },
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/orders/order_id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.orders.getOrder({
            order_id: "order_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getOrder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/orders/order_id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.orders.getOrder({
                order_id: "order_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("getOrderTimeline (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            order_id: "order_id",
            current_status: "pending",
            milestones: [
                {
                    type: "order_created",
                    label: "label",
                    occurred_at: "2024-01-15T09:30:00Z",
                    source: "source",
                    detail: { key: "value" },
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/orders/order_id/timeline")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.orders.getOrderTimeline({
            order_id: "order_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getOrderTimeline (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/orders/order_id/timeline")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.orders.getOrderTimeline({
                order_id: "order_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("cancelOrder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/orders/order_id/cancel").respondWith().statusCode(200).build();

        const response = await client.orders.cancelOrder({
            order_id: "order_id",
        });
        expect(response).toEqual(undefined);
    });

    test("cancelOrder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/orders/order_id/cancel")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.orders.cancelOrder({
                order_id: "order_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
