// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PaymentsClient", () => {
    test("getPendingPayment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            status: "requires_action",
            order_id: "order_id",
            pay_url: "pay_url",
            expires_at: "2024-01-15T09:30:00Z",
            quote: { max_price_cents: 1, order_fee_cents: 1, stripe_fee_cents: 1, hold_cents: 1 },
            products: [{ url: "url", quantity: 1 }],
            client: { name: "name", url: "url" },
            ship_to_summary: "ship_to_summary",
        };

        server
            .mockEndpoint()
            .get("/payments/payment_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.getPendingPayment({
            payment_id: "payment_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPendingPayment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/payments/payment_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.getPendingPayment({
                payment_id: "payment_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("createCheckoutSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { url: "url" };

        server
            .mockEndpoint()
            .post("/payments/payment_id/checkout-session")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.createCheckoutSession({
            payment_id: "payment_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createCheckoutSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/payments/payment_id/checkout-session")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.createCheckoutSession({
                payment_id: "payment_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
