// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ProductsClient", () => {
    test("searchProducts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "status",
            results: [
                {
                    product_id: "product_id",
                    title: "title",
                    image: "image",
                    brand: "brand",
                    price: 1,
                    stars: 1.1,
                    num_reviews: 1,
                    num_offers_estimate: 1,
                    num_sales: 1,
                    fresh: true,
                    prime: true,
                    pantry: true,
                    addon: true,
                    ship_price: 1,
                    upc: "upc",
                    mpn: "mpn",
                    available: true,
                    available_online: true,
                    available_instore: true,
                    freight_shipping: true,
                    preorder: true,
                    first_party_seller: true,
                    buyapi_hint: true,
                    url: "url",
                    variant_id: "variant_id",
                    currency_code: "currency_code",
                },
            ],
            next_page: 1,
        };

        server.mockEndpoint().get("/products/search").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.products.searchProducts({
            query: "query",
            retailer: "retailer",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("searchProducts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/products/search").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.products.searchProducts({
                query: "x",
                retailer: "retailer",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("getProductOffers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "completed" };

        server
            .mockEndpoint()
            .get("/products/product_id/offers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.getProductOffers({
            product_id: "product_id",
            retailer: "retailer",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getProductOffers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/products/product_id/offers")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.getProductOffers({
                product_id: "product_id",
                retailer: "retailer",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("getProductDetails (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "completed" };

        server
            .mockEndpoint()
            .get("/products/product_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.getProductDetails({
            product_id: "product_id",
            retailer: "retailer",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getProductDetails (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/products/product_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.getProductDetails({
                product_id: "product_id",
                retailer: "retailer",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
