// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ReturnsClient", () => {
    test("listReturnRequests (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            return_requests: [
                {
                    id: "id",
                    order_id: "order_id",
                    status: "open",
                    reason: "damaged",
                    notes: "notes",
                    resolution_notes: "resolution_notes",
                    items: [{ order_item_id: "order_item_id", quantity: 1 }],
                    label_urls: ["label_urls"],
                    merchant_return_id: "merchant_return_id",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            total: 1,
        };

        server.mockEndpoint().get("/returns").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.returns.listReturnRequests();
        expect(response).toEqual(rawResponseBody);
    });

    test("listReturnRequests (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/returns").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.returns.listReturnRequests();
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("createReturnRequest (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            order_id: "order_id",
            items: [{ order_item_id: "order_item_id", quantity: 1 }],
            reason: "damaged",
        };
        const rawResponseBody = {
            id: "id",
            order_id: "order_id",
            status: "open",
            reason: "damaged",
            notes: "notes",
            resolution_notes: "resolution_notes",
            items: [{ order_item_id: "order_item_id", quantity: 1 }],
            label_urls: ["label_urls"],
            merchant_return_id: "merchant_return_id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/returns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.returns.createReturnRequest({
            order_id: "order_id",
            items: [
                {
                    order_item_id: "order_item_id",
                    quantity: 1,
                },
            ],
            reason: "damaged",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createReturnRequest (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            order_id: "order_id",
            items: [
                { order_item_id: "order_item_id", quantity: 100 },
                { order_item_id: "order_item_id", quantity: 100 },
            ],
            reason: "damaged",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/returns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.returns.createReturnRequest({
                order_id: "order_id",
                items: [
                    {
                        order_item_id: "order_item_id",
                        quantity: 100,
                    },
                    {
                        order_item_id: "order_item_id",
                        quantity: 100,
                    },
                ],
                reason: "damaged",
            });
        }).rejects.toThrow(Zinc.ConflictError);
    });

    test("createReturnRequest (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            order_id: "order_id",
            items: [
                { order_item_id: "order_item_id", quantity: 100 },
                { order_item_id: "order_item_id", quantity: 100 },
            ],
            reason: "damaged",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/returns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.returns.createReturnRequest({
                order_id: "order_id",
                items: [
                    {
                        order_item_id: "order_item_id",
                        quantity: 100,
                    },
                    {
                        order_item_id: "order_item_id",
                        quantity: 100,
                    },
                ],
                reason: "damaged",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("getReturnRequest (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            order_id: "order_id",
            status: "open",
            reason: "damaged",
            notes: "notes",
            resolution_notes: "resolution_notes",
            items: [{ order_item_id: "order_item_id", quantity: 1 }],
            label_urls: ["label_urls"],
            merchant_return_id: "merchant_return_id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/returns/return_request_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.returns.getReturnRequest({
            return_request_id: "return_request_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getReturnRequest (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/returns/return_request_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.returns.getReturnRequest({
                return_request_id: "return_request_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
