// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SearchClient", () => {
    test("search (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "status",
            query: "query",
            results: [
                {
                    url: "url",
                    retailer: "retailer",
                    title: "title",
                    image: "image",
                    brand: "brand",
                    price: 1,
                    stars: 1.1,
                    num_reviews: 1,
                    available: true,
                },
            ],
            excluded_by_price: 1,
            hint: "hint",
        };

        server.mockEndpoint().get("/search").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.search.search({
            q: "q",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("search (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/search").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.search.search({
                q: "x",
            });
        }).rejects.toThrow(Zinc.PaymentRequiredError);
    });

    test("search (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/search").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.search.search({
                q: "x",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
