// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TrackingClient", () => {
    test("getPublicTracking (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            order_id: "order_id",
            current_status: "pending",
            estimated_delivery_date: "estimated_delivery_date",
            destination: {
                address_line1: "address_line1",
                address_line2: "address_line2",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
            shipments: [
                {
                    carrier: "carrier",
                    tracking_number: "tracking_number",
                    status: "pending",
                    estimated_delivery_date: "2023-01-15",
                    checkpoints: [{ checkpoint_time: "2024-01-15T09:30:00Z", status: "pending", message: "message" }],
                },
            ],
            items: [{ url: "url", quantity: 1, status: "pending" }],
        };

        server.mockEndpoint().get("/track/order_id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tracking.getPublicTracking({
            order_id: "order_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPublicTracking (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/track/order_id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tracking.getPublicTracking({
                order_id: "order_id",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
