// This file was auto-generated by Fern from our API Definition.

import * as Zinc from "../../src/api/index";
import { ZincClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhooksClient", () => {
    test("getWebhookEndpoint (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { webhook_url: "webhook_url", webhook_secret: "webhook_secret" };

        server.mockEndpoint().get("/webhooks/endpoint").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.webhooks.getWebhookEndpoint();
        expect(response).toEqual(rawResponseBody);
    });

    test("getWebhookEndpoint (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/webhooks/endpoint").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhookEndpoint();
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("setWebhookEndpoint (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "https://example.com/zinc/webhook" };
        const rawResponseBody = { webhook_url: "webhook_url", webhook_secret: "webhook_secret" };

        server
            .mockEndpoint()
            .put("/webhooks/endpoint")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.setWebhookEndpoint({
            url: "https://example.com/zinc/webhook",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("setWebhookEndpoint (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/webhooks/endpoint")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.setWebhookEndpoint({
                url: "url",
            });
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });

    test("clearWebhookEndpoint (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/webhooks/endpoint").respondWith().statusCode(200).build();

        const response = await client.webhooks.clearWebhookEndpoint();
        expect(response).toEqual(undefined);
    });

    test("clearWebhookEndpoint (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZincClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/webhooks/endpoint")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.clearWebhookEndpoint();
        }).rejects.toThrow(Zinc.UnprocessableEntityError);
    });
});
