// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Zinc from "../../../index.js";

export declare namespace UsageClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class UsageClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<UsageClient.Options>;

    constructor(options: UsageClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * The caller's own data-API usage over a trailing window, per endpoint.
     *
     * @param {Zinc.GetMyUsageUsageGetRequest} request
     * @param {UsageClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zinc.UnprocessableEntityError}
     * @throws {@link errors.ZincError}
     * @throws {@link errors.ZincTimeoutError}
     *
     * @example
     *     await client.usage.getMyUsage()
     */
    public getMyUsage(
        request: Zinc.GetMyUsageUsageGetRequest = {},
        requestOptions?: UsageClient.RequestOptions,
    ): core.HttpResponsePromise<Zinc.UserUsageResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getMyUsage(request, requestOptions));
    }

    private async __getMyUsage(
        request: Zinc.GetMyUsageUsageGetRequest = {},
        requestOptions?: UsageClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zinc.UserUsageResponse>> {
        const { window_days: windowDays, recent, authorization } = request;
        const _queryParams: Record<string, unknown> = {
            window_days: windowDays,
            recent,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ authorization: authorization ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZincEnvironment.Production,
                "usage",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Zinc.UserUsageResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Zinc.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZincError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/usage");
    }
}
