// This file was auto-generated by Fern from our API Definition.

import { AgentClient } from "./api/resources/agent/client/Client.js";
import { HealthClient } from "./api/resources/health/client/Client.js";
import { ManagedAccountsClient } from "./api/resources/managedAccounts/client/Client.js";
import { OrdersClient } from "./api/resources/orders/client/Client.js";
import { ProductsClient } from "./api/resources/products/client/Client.js";
import { RetailersClient } from "./api/resources/retailers/client/Client.js";
import { ReturnsClient } from "./api/resources/returns/client/Client.js";
import { SearchClient } from "./api/resources/search/client/Client.js";
import { TrackingClient } from "./api/resources/tracking/client/Client.js";
import { UsageClient } from "./api/resources/usage/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace ZincClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ZincClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ZincClient.Options>;
    protected _orders: OrdersClient | undefined;
    protected _products: ProductsClient | undefined;
    protected _search: SearchClient | undefined;
    protected _managedAccounts: ManagedAccountsClient | undefined;
    protected _agent: AgentClient | undefined;
    protected _returns: ReturnsClient | undefined;
    protected _retailers: RetailersClient | undefined;
    protected _usage: UsageClient | undefined;
    protected _tracking: TrackingClient | undefined;
    protected _health: HealthClient | undefined;

    constructor(options: ZincClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get orders(): OrdersClient {
        return (this._orders ??= new OrdersClient(this._options));
    }

    public get products(): ProductsClient {
        return (this._products ??= new ProductsClient(this._options));
    }

    public get search(): SearchClient {
        return (this._search ??= new SearchClient(this._options));
    }

    public get managedAccounts(): ManagedAccountsClient {
        return (this._managedAccounts ??= new ManagedAccountsClient(this._options));
    }

    public get agent(): AgentClient {
        return (this._agent ??= new AgentClient(this._options));
    }

    public get returns(): ReturnsClient {
        return (this._returns ??= new ReturnsClient(this._options));
    }

    public get retailers(): RetailersClient {
        return (this._retailers ??= new RetailersClient(this._options));
    }

    public get usage(): UsageClient {
        return (this._usage ??= new UsageClient(this._options));
    }

    public get tracking(): TrackingClient {
        return (this._tracking ??= new TrackingClient(this._options));
    }

    public get health(): HealthClient {
        return (this._health ??= new HealthClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
