// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../../../../index.js";

/**
 * @example
 *     {
 *         product_id: "product_id",
 *         retailer: "amazon"
 *     }
 */
export interface AgentProductOffersRequest {
    /** Product identifier (e.g. ASIN) */
    product_id: string;
    /** Retailer: amazon or walmart */
    retailer: Zinc.AgentProductOffersRequestRetailer;
    /** Max response age in seconds, at least 31 (mutually exclusive with newer_than) */
    max_age?: number | null;
    /** Minimum retrieval timestamp, as a unix time (mutually exclusive with max_age). Windows shorter than 31s are widened to it. */
    newer_than?: number | null;
    /** Return immediately with status=processing */
    async?: boolean | null;
}
