// This file was auto-generated by Fern from our API Definition.

import type * as Zinc from "../../../../index.js";

/**
 * @example
 *     {
 *         product_id: "product_id",
 *         retailer: "amazon"
 *     }
 */
export interface AgentProductDetailsPostRequest {
    /** Product identifier (e.g. ASIN) */
    product_id: string;
    /** Retailer: amazon or walmart */
    retailer: Zinc.AgentProductDetailsPostRequestRetailer;
    /** Max response age in seconds */
    max_age?: number | null;
    /** Minimum retrieval timestamp */
    newer_than?: number | null;
    /** Return immediately with status=processing */
    async?: boolean | null;
}
