// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         q: "q"
 *     }
 */
export interface AgentSearchPostRequest {
    /** Search term */
    q: string;
}
